### ISSUE TITLE
Allow kvm to manage KRE versions for other platforms

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnvm#136]
_From @bgourlie on January 15, 2015 15:40_

I'd like it if kvm on Linux/OS X were able to pull down the Windows KRE, or kvm on Windows pull down the mono KRE.  The obvious use-case for this is building and packing an asp.net app on one platform that targets another.

I have this mostly working already -- building and deploying to Azure from a linux vm on travis-ci, but I hack it by manually copying `KRE-CLR-x86.1.0.0-*` to `.kre/packages/`.  If I were able to automate this entirely through kvm, it would be most excellent.

_Copied from original issue: aspnet/KRuntime#1073_

**Comment by muratg** [comment]
dnvm -os
