### ISSUE TITLE
Provide a way to delete an installed version of KRE

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnvm#14]
For example I want to delete some old version of installed KRE, kvm should provide a way to delete them. Currently it is a manual folder delete. 

This is similar to https://github.com/aspnet/KRuntime/issues/319, but this item is to delete the KRE not the alias. By this we delete the KRE, but the alias still lives. 

From https://github.com/aspnet/KRuntime/issues/322

**Comment by xanather** [comment]
Has this been added? I am currently on 1.0.0-beta4 - no uninstall command. I was unsure if it is safe to delete the run time folder but I'll be doing it anyway.

**Comment by muratg** [comment]
@xanather it's not added, and it should be safe to delete the runtime folder.

Closing this as https://github.com/aspnet/dnvm/issues/254 tracks the suggestion

**Comment by taraslayshchuk** [comment]
+1
