### ISSUE TITLE
'kvm use -p' on Windows 10 doesn't persist across different prompts

### ISSUE THREAD

**Issue by troydai** [aspnet/dnvm#161]
The original issue was opened in `Home` repo https://github.com/aspnet/Home/issues/341. 

I moved it here:

>@shanselman and I are both seeing strange behavior on Windows 10 machines when trying to run `kvm use -p`. If you open a VS dev cmd prompt, a standard cmd prompt, and a PowerShell prompt, and try `kvm use -p` in each one and then reopening the other prompts, you'll see that it doesn't stick properly.

>On @shanselman's machine, the VS dev cmd prompt never gets an active session to stick across prompts. On mine, the PS prompt always had a different active KRE to the other two prompts.

>Trying the same thing on my Windows 8.1 machine worked as expected.

**Comment by troydai** [comment]
@DamianEdwards

**Comment by troydai** [comment]
I can repo this issue on Windows 10 build 9926.

**Comment by troydai** [comment]
https://github.com/aspnet/dotnetsdk/blob/dev/src/kvm.ps1#L1163

The `[Environment]::SetEnvironmentVariable` behaves differently on Windows 10.

**Comment by shanselman** [comment]
Digging into this.

* SETX in a standard Windows 10 command prompt takes 10 seconds! It's instantaneous on Windows 8
* SETX doesn't stick when run in a non-admin command prompt
* [Environment]::SetEnvironmentVariable("PATH"), $userPath, "User") also takes a long time and doesn't stick.

Therefore, there's some Win10 regression in the underlying Win32 API around Env Vars, IMHO. 

Is this known?

**Comment by shanselman** [comment]
WORKAROUND: This works (even though the SET is SLOW) from an Admin Prompt for now....

**Comment by DamianEdwards** [comment]
That's slightly diff to what I'm seeing, but I launch PowerShell as admin all the time from a pinned shortcut on the task bar

**Comment by troydai** [comment]
It's not repo for me on 11041 build. 

/cc @shanselman @DamianEdwards is this still an issue for you?
