### ISSUE TITLE
dnvm upgrade does *not* set the active dnx if it's already installed

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnvm#186]
Another regression since the rewrite. When running dvnm upgrade, it doesn't update the active dnx:

![image](https://cloud.githubusercontent.com/assets/95136/6746866/2f9e6ecc-ce8d-11e4-8580-279d26b41d09.png)

However, if I delete and run upgrade again, it sets the path:

![image](https://cloud.githubusercontent.com/assets/95136/6746875/5f799234-ce8d-11e4-9150-652fbc316dab.png)

**Comment by glennc** [comment]
Looks like this works now.
