### ISSUE TITLE
Give ability to see the runtime name / path in `dnvm list` output instead of having a separate name command to compose the runtime name. 

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnvm#197]
Give ability to see the runtime name / path in `dnvm list` output instead of having a separate name command to compose the runtime name. 

This is most useful when trying to do a `dnu bundle --runtime`. Easiest way is to do a `dnvm list` to see the list of available runtimes and choose one or more among that.

**Comment by glennc** [comment]
We have an issue to make it easier to specify --runtime.
