### ISSUE TITLE
dnvm install fails when the nupkg path contains spaces and thus needs to be in double quotes on windows

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnvm#202]
![dnvm-install-error](https://cloud.githubusercontent.com/assets/1424265/6926954/d5bd0380-d79e-11e4-8bbd-dfc016a4db40.jpg)

**Comment by PradeepKadubandi** [comment]
Here's the full command and message : 

C:\Users\pradeek>dnvm install "C:\Program Files (x86)\Microsoft Web Tools\DNX\dnx-coreclr-win-x64.1.0.0-beta5-11380.nupkg"
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a p
ath was included, verify that the path is correct and try again.
At line:1 char:249
+ ... Program Files (x86)\Microsoft Web Tools\DNX\dnx-coreclr-win-x64.1.0.0-beta5-1138 ...
+                    ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PradeepKadubandi** [comment]
A simple work around is to use single quotes instead of double quotes which I can use for now, but this issue needs to be investigated and fixed eventually...

**Comment by glennc** [comment]
Change to allow consistent escaping is here: https://github.com/aspnet/dnvm/pull/309
