### ISSUE TITLE
`dnvm install` should not change user's path

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnvm#205]
This command is documented as a small subset of `dnvm upgrade`.  However it changes the current path and, if `-persistent` is specified, the user's stored path.  These changes just get in the way, requiring `dnvm use` commands to get back where the user was.

**Comment by dougbu** [comment]
recommend removing `-persistent` entirely from this command

**Comment by glennc** [comment]
What is the scenario where you want to install a runtime and then not use it?

**Comment by dougbu** [comment]
- downloading a few different runtimes at once; then run tests with each
- standard `build.cmd` stuff as well

**Comment by davidfowl** [comment]
I'm going to agree with @dougbu on this one. We need a way to do this. I wrote a build script recently and I wanted to install a specific version of the dnx, then use dnvm exec to execute commands with specific versions
