### ISSUE TITLE
Aliases seem to ignore runtime

### ISSUE THREAD

**Issue by anurse** [aspnet/dnvm#214]
Repro steps:
1. `dnvm install latest -r coreclr -a test_coreclr`
2. `dnvm use none`
3. `dnvm use test_coreclr`

Expected: Active DNX is the coreclr variant of the DNX installed by step 1
Actual: Either "Cannot find dnx-clr..." or the Desktop CLR variant is selected (depending on if you have the Desktop CLR variant installed.

**Comment by GuardRex** [comment]
Related? Providing an alias by itself isn't enough to specify from among **only** CoreCLR runtimes:
For runtimes ...
```
Active Version           Runtime Architecture Location Alias
------ -------           ------- ------------ -------- -----
       1.0.0-beta5-11560 coreclr x64          <path>
  *    1.0.0-beta5-11561 coreclr x64          <path>
       1.0.0-beta5-11562 coreclr x64          <path>
       1.0.0-beta5-11565 coreclr x64          <path>   default
```
Trying ...
```
dnvm use default
```
Results in ...
```
<path>\.dnx\bin\dnvm.ps1 : Cannot find dnx-clr-win-x64.1.0.0-beta5-11565 ...
```
(note `-clr-` is attempted) but ...
```
dnvm use default -r coreclr
```
works.

**Comment by GuardRex** [comment]
My comment is also a dup #175

**Comment by anurse** [comment]
Yeah, definitely a dup of #175.
