### ISSUE TITLE
Make dnvm native image generation story more consistent and on by default

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnvm#216]
We try to crossgen by default and ngen by default. Unfortunately, ngen requires admin privileges, which requires a prompt. Instead, we compromised and chose not to prompt for full CLR which means that the install experience is inconsistent between the 2 (`dnvm install --NoNative` vs `dnvm install --native`).

On top of that, the ngen pops up an ugly dialog and cross gen takes a long time and shows no progress bar. 

Time to polish:

- Always `ngen` or `crossgen` as it speeds up roslyn compilation by miles (shaves 3+ seconds just to compile *ANYTHING*). We can add a -NoPrompt in the ngen case if the user wants to avoid elevating to admin. Scripting should be easy so we should allow disabling prompting.
- Show progress when running `ngen` or `crossgen` - Just to make it easier to wait
- Make it easy to undo and redo `ngen` or `crossgen` - In case modifications are made to the dnx folder (during development etc)

**Comment by anurse** [comment]
> We can add a -NoPrompt in the ngen case if the user wants to avoid elevating to admin.

*barf* ... not that I can think of a better idea...

**Comment by muratg** [comment]
Closing.
