### ISSUE TITLE
dnvm upgrade failed

### ISSUE THREAD

**Issue by qucc** [aspnet/dnvm#227]
I follow https://github.com/aspnet/Home document and then I run "dnvm upgrade" to install dnx. but it failed. here is the error
.There are no runtimes matching the name dnx-clr-win-x86 on feed https://www.nug
et.org/api/v2.

**Comment by GuardRex** [comment]
I may have just had the same issue ... try adding a `-Unstable` parameter to it if you were trying to get the dev feed.

**Comment by ahmedshuhel** [comment]
@GuardRex Thanks! That worked.

**Comment by muratg** [comment]
Yup, @GuardRex is right.

**Comment by moutono** [comment]
Amen brother, worked like a charm

**Comment by muratg** [comment]
@moutono now that ASP.NET Core 1 is out, I recommend updating to dotnet tooling and RTM packages.

**Comment by moutono** [comment]
Thanks for the feedback. Will do that now.
