### ISSUE TITLE
dnvm use with -p argument fails on Linux

### ISSUE THREAD

**Issue by MattGal** [aspnet/dnvm#229]
On linux:
 dnvm use 1.0.0-beta5 -r coreclr -arch x64
Adding /home/matt/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5/bin to process PATH

but:
dnvm use 1.0.0-beta5 -r coreclr -arch x64 -p
Adding /home/matt/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5-matell/bin to process PATH
******
dnx-mono.1.0.0-beta5-matell is not an installed DNX version
*****
@ellismg

**Comment by muratg** [comment]
@glennc

**Comment by glennc** [comment]
This appears to be fixed in the version of DNVM we just tried it on.
