### ISSUE TITLE
dnvm exec throws NullReferenceException

### ISSUE THREAD

**Issue by roji** [aspnet/dnvm#232]
With dnvm v1.0.0-beta5-10368, running `dnvm exec default c:\windows\notepad.exe`, I get:

```
dnvm-exec : Object reference not set to an instance of an object.
At C:\Users\teamcity_agent\.dnx\bin\dnvm.ps1:1431 char:9
+         & "dnvm-$cmd" @cmdargs
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [dnvm-exec], NullReference
   Exception
    + FullyQualifiedErrorId : System.NullReferenceException,dnvm-exec
```

**Comment by muratg** [comment]
@roji Couldn't repro this with dnvm v1.0.0-beta5-10371.  Same command line launches notepad :)

Could you upgrade and retry?

**Comment by roji** [comment]
Weird, works v1.0.0-beta5-10371, was either fixed or some weird issue with my setup, thanks for your time!
