### ISSUE TITLE
Conflict With K

### ISSUE THREAD

**Issue by paranoid-android** [aspnet/dnvm#242]
I am trying to update my existing setup so that I can get started with [ASP.NET 5 on OS X](http://docs.asp.net/en/latest/getting-started/installing-on-mac.html). Previously, I installed the K runtime. I could successfully run ASP.NET 5 apps by using the `k run` command from a terminal window. However, I am now trying to get this updated. 

While following the instructions found in the ASP.NET 5 on OS X link, I received the following error:
`Could not create link for aspnet/dnx/kvm, as it conflicts with aspnet/k/kvm`

I received that error when I ran `brew tap aspnet/dnx`. 

How do I get around this conflict? I'm not sure how to fix this. Thank you!

**Comment by Eilon** [comment]
Not exactly sure how the brew stuff works, but you need to remove/uninstall any old "k" named stuff installed from previous brews. All the new stuff is named "dnx", "dnvm" etc.

**Comment by paranoid-android** [comment]
@Eilon I believe I have uninstalled the old `k` stuff. If I run `k -h` or `kvm -h`, I receive a `command not found` error. If I run `brew list`, I only see `git` listed. I cannot figure out why I'm still getting this error. Any help is appreciated. I'm sure others will have this issue.

**Comment by anurse** [comment]
The problem is that the old 'aspnet/k' Brew tap conflicts with 'aspnet/dnx'. You need to run `brew untap aspnet/k` before you run `brew tap aspnet/dnx`

**Comment by muratg** [comment]
@paranoid-android 
```
brew uninstall kvm
brew untap aspnet/k
brew update
brew tap aspnet/dnx
brew install dnvm
```

**Comment by chadcampbell** [comment]
@muratg Bravo! That's the winner. Thank you so much.

**Comment by anurse** [comment]
I submitted aspnet/Docs#178 to help clear this up a little.

**Comment by chadcampbell** [comment]
@muratg - I was having the same issue. This script worked for me.

**Comment by muratg** [comment]
@chadcampbell Glad it helped. @paranoid-android If you're still having issues, please reactivate.
