### ISSUE TITLE
dnvm.sh shows no output (OSX)

### ISSUE THREAD

**Issue by iainfogg** [aspnet/dnvm#243]
When I run `dnvm.sh` on a Mac, it shows no output at all, even though commands like `list` are supposed to show something.

It was installed through homebrew.

**Comment by panesofglass** [comment]
I experience the same behavior. What's supposed to be in that file?

**Comment by davidfowl** [comment]
Did you ever install any dnx runtimes?

**Comment by panesofglass** [comment]
Yep. `brew install dnx` installed `1.0.0-beta4`. I see it now when I run `dnvm list`.

**Comment by panesofglass** [comment]
Searching my Mac, I don't see any other copies of `dnvm.sh` except the one I manually created.

**Comment by iainfogg** [comment]
The only stuff I've got installed is from following the instructions at https://github.com/aspnet/home

I have dnx-mono.1.0.0-beta4 in ~./.dnx/runtimes

I tried uninstalling and reinstalling dnvm with the same results.

**Comment by glennc** [comment]
If you upgrade DNVM now does this still happen? I will either close this or assign it to a milestone.

**Comment by iainfogg** [comment]
Hi @glennc - just to confirm, I am now on beta5 and it works fine. 

Just as an aside, after waiting several months for someone to comment, it would have been good to have had more than a day to reply to you before it was closed.

Thanks, Iain
