### ISSUE TITLE
dnvm.sh isn't changing PATH on OSX

### ISSUE THREAD

**Issue by iainfogg** [aspnet/dnvm#244]
When I run `dnvm.sh` on a Mac it's not making any changes to the PATH environment variable, therefore the `dnx` command won't run (unless I manually update the path myself).

It was installed through Homebrew as per https://github.com/aspnet/Home#os-x

**Comment by glennc** [comment]
@iainfogg It has been a while since you filed this. Does it still happen? What version of the DNVM are you using, if you upgrade to a new DNVM does it still break? Can you show me the output of `DNVM use` when it is breaking?

**Comment by iainfogg** [comment]
Hi @glennc - since I moved to beta5 it sorted itself out.

Thanks, Iain
