### ISSUE TITLE
dnvm update-self not working on mac

### ISSUE THREAD

**Issue by Gutek** [aspnet/dnvm#246]
to install it on mac your instructions ask to use homebrew, however, because we are using homebrew we can't just do `dnvm update-self` as this will cause:

```
~/.dnx/dnvm/dnvm.sh doesn't exist. This command assumes you have installed dnvm in the usual location and are trying to update it. If you want to use update-self then dnvm.sh should be sourced from ~/.dnx/dnvm
```

at least provide information that on mac this will not work, or say how to `update-self` on mac

**Comment by damnhandy** [comment]
+1 same problem here

**Comment by aliozgur** [comment]
+ same here

**Comment by kalch** [comment]
+1

**Comment by salerth** [comment]
This can be fixed by adding a link between the brew location and the expected location:
`mkdir ~/.dnx/dnvm; ln -s /usr/local/Cellar/dnvm/1.0.0-dev/bin/dnvm.sh ~/.dnx/dnvm/dnvm.sh`

It means you are updating the homebrew file outside of homebrew though which isn't awesome, but it works!

**Comment by aheil** [comment]
+1 can confirm this issue

**Comment by natemcmaster** [comment]
+1 still an issue.

**Comment by muratg** [comment]
cc @glennc

**Comment by glennc** [comment]
We are moving away from Homebrew in favor of other methods of getting DNVM and DNX. Specifically a pkg that will install DNVM and/or the DNX for you. If you use that or the curl way of installing then this will work.

**Comment by phillijw** [comment]
I've seen that this still happens for people that have installed via homebrew and then installed via the package later on
