### ISSUE TITLE
dnvm help for alias command is not updated

### ISSUE THREAD

**Issue by jeremymeng** [aspnet/dnvm#247]
The `-r` and `-a` options are now supported, but the help message hasn't been updated.

**Comment by Eilon** [comment]
@glennc this is you, right?

@jeremymeng is this PowerShell, shell script, both?

**Comment by jeremymeng** [comment]
Shell script. I haven't checked PowerShell.

**Comment by jeremymeng** [comment]
PowerShell help shows them.

**Comment by Eilon** [comment]
OK definitely @glennc I think then :smile:

**Comment by muratg** [comment]
This is fixed now :)
