### ISSUE TITLE
Add override feed help text on Windows

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnvm#249]
@glennc

**Comment by glennc** [comment]
You mean this text: ``You can control the URL of the stable and unstable channel by setting the DNX_FEED and DNX_UNSTABLE_FEED variables.``?

**Comment by BrennanConroy** [comment]
Yep

**Comment by glennc** [comment]
This has already been done, helping @BrennanConroy out by closing the issues for work he has done...
