### ISSUE TITLE
dnvm.ps1 should use Set-StrictMode -Version Latest

### ISSUE THREAD

**Issue by maximpashuk** [aspnet/dnvm#251]
It is just a best practice

http://blogs.technet.com/b/heyscriptingguy/archive/2014/12/03/enforce-better-script-practices-by-using-set-strictmode.aspx

http://viziblr.com/news/2013/4/4/two-tips-for-c-developers-trying-to-learn-powershell-set-str.html

If dnvm.ps1 will be bewrited with latest strict mode and erroractionpreference, then code will be more readable

**Comment by bcdev-com** [comment]
More than just best practices, the current version of dnvm.ps1 fails spectacularly when run from a PowerShell session that had Set-StrictMode turned on in the profile.   At the very least, _dnvm.ps1 needs to have a "Set-StrictMode -Off" added at the top of the file_ so it runs correctly when launched from a StrictMode runspace.

On a related note, why are there repeated uses of "-ExecutionPolicy Unrestricted" in the instructions and code.  It appears they would all work with "-ExecutionPolicy RemoteSigned".  Least privilege is an important principle.

**Comment by glennc** [comment]
The script should work in StrictMode. We will look at fixing the problems that stop it. I also think that we sign dnvm,ps1 now.
