### ISSUE TITLE
dnvm uninstall

### ISSUE THREAD

**Issue by jchannon** [aspnet/dnvm#254]
how do i delete a version? i can't see any command such as `dnvm uninstall`

**Comment by davidfowl** [comment]
Go to the folder and hit the delete button on the version you want to uninstall.

**Comment by jchannon** [comment]
thats fine but i think if you have an install you should have an uninstall

**Comment by muratg** [comment]
Agreed. @glennc can you have a look when you're back from Ignite?

**Comment by glennc** [comment]
Sure, I can look at it now that I'm back.

**Comment by moozzyk** [comment]
Looks like deleting the runtime folder is not enough. You will leave behind alias files if the runtime you have deleted was aliased.

**Comment by tugberkugurlu** [comment]
I was always **assuming** dnvm had `uninstall`. Taught me a lesson that I will never assume anymore :smile:

**Comment by jchannon** [comment]
You know what they say about assumptions ;)

**Comment by JasonSoft** [comment]
+1

**Comment by sayedihashimi** [comment]
+1 this is needed

**Comment by muratg** [comment]
@BrennanConroy now owns DNVM. I think it would be good to get this in in beta 7.

**Comment by niemyjski** [comment]
+1 I have 4 versions installed It would be nice to be able to uninstall or uninstall on upgrade.

**Comment by glennc** [comment]
The PR is out, just needs to be reviewed and merged.

**Comment by jchannon** [comment]
Link?

**Comment by glennc** [comment]
Linked on this already: https://github.com/aspnet/dnvm/pull/375

**Comment by muratg** [comment]
@BrennanConroy PR for this is out for a long time. Are you going to check this in in Beta 8?

**Comment by BrennanConroy** [comment]
Ya, need to update it since global install went in, will do this week.

**Comment by BrennanConroy** [comment]
6479d250bb15fce17afcc204582849231334f479

**Comment by Nomad-IC** [comment]
wich folder (-s) i must delete for uninstalling?

**Comment by BrennanConroy** [comment]
You can just use dnvm to uninstall or delete the specific runtime in the .dnx/runtimes folder

**Comment by aligneddev** [comment]
I don't see it in dnvm 1.0.0-rc1-update1 clr as an option. It is an "unknown command".

Is that expected?

**Comment by BrennanConroy** [comment]
Are you typing `dnvm uninstall` ?

**Comment by aligneddev** [comment]
yes, this might be my misunderstanding. Do I have an outdated dnvm version? I have 1.0.0-rc1-update1 clr and coreclr listed.
![dnvm](https://cloud.githubusercontent.com/assets/1636977/13859510/cdcbf7b2-ec51-11e5-8c71-99727bce7b3f.png)

**Comment by BrennanConroy** [comment]
Yes, your version of dnvm is beta5-10384

**Comment by aligneddev** [comment]
Yes, I just ran dnvm update-self. I didn't realize before I posted that dnvm didn't get updated when I installed dot net core rc1. Thank you.
