### ISSUE TITLE
Use the term "runtime type" instead of "runtime flavor"

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnvm#255]
See the help info following `-r` option
![capture](https://cloud.githubusercontent.com/assets/1383883/7466262/c51d8cb4-f294-11e4-9f11-757f35716931.PNG)

`dnvm` is using the term `runtime flavor` while runtime itself uses `runtime type`:
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Abstractions/IRuntimeEnvironment.cs#L27

We should make them consistent.

@davidfowl @glennc @muratg

**Comment by muratg** [comment]
Is there a well-known term for this?  I heard people using "flavor" before, but I couldn't really find any definitive source for this.

**Comment by ChengTian** [comment]
Yeah, that's the problem. We are using the term `flavor` in runtime functional tests and dnvm. However, newly added runtime environment is using `RuntimeType`.

Seems @victorhurdugaci added `RuntimeType` in `IRuntimeEnvironment`. @victorhurdugaci , what's the source you used as reference when you were adding this?

**Comment by victorhurdugaci** [comment]
I think we should use `runtimeFramework`. Most users know .NET as a `framework` so saying that the framework is CoreCLR or CLR sounds natural.

**Comment by victorhurdugaci** [comment]
Thought, according to the [dictionary](http://www.merriam-webster.com/dictionary/flavor) "flavor" can also mean:

- characteristic or predominant quality 
- a property that distinguishes different types of elementary particles

**Comment by ChengTian** [comment]
I guess `runtimeFramework` should be used to refer to the target framework of a runtime, which is `DNXCore,Version=v5.0` or `DNX,Version=v4.5.1`. For `CLR/CoreCLR`, it's better to choose between `runtime flavor` and `runtime type`.

**Comment by Bartmax** [comment]
:+1: flavor
