### ISSUE TITLE
DVNM upgrade of unstable (-u) DNX fails

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/dnvm#256]
2015 RC 1 Installed.

Ran the following command (just to make sure I have the latest DNVM):

***
C:\>@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent
.com/aspnet/Home/dev/dnvminstall.ps1'))}"
Using temporary directory: C:\Users\tdu\AppData\Local\Temp\2\dnvminstall
Downloading DNVM.ps1 to
Downloading DNVM.cmd to
Installing DNVM
Installing .NET Version Manager to C:\Users\tdu\.dnx\bin
Installing 'dnvm.ps1' to 'C:\Users\tdu\.dnx\bin' ...
  Skipping: file already exists
Installing 'dnvm.cmd' to 'C:\Users\tdu\.dnx\bin' ...
  Skipping: file already exists
Adding C:\Users\tdu\.dnx\bin to Process PATH
Adding C:\Users\tdu\.dnx\bin to User PATH
Adding C:\Users\tdu\.dnx to Process DNX_HOME
Adding C:\Users\tdu\.dnx to User DNX_HOME
***

Ran the following command to upgrade the DNX:

***
C:\>dnvm upgrade -u
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : A parameter cannot be found that matches parameter name 'u'.
At line:1 char:180
+ ... t-envvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade -u
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dnvm.ps1

C:\>dnvm upgrade -unstable
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : A parameter cannot be found that matches parameter name 'unstable'.
At line:1 char:180
+ ... t-envvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade -unstabl ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dnvm.ps1

***

FYI:

***
C:\>dnvm list

Active Version           Runtime Architecture Location                   Alias
       1.0.0-beta4       clr     x64          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4-11566 clr     x86          C:\Users\tdu\.dnx\runtimes default, u
       1.0.0-beta5-11672 clr     x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta5-11672 coreclr x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta5-11682 clr     x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta5-11682 coreclr x86          C:\Users\tdu\.dnx\runtimes
***

**Comment by jsacapdev** [comment]
This is because there are two DNVM being resolved in the path:

C:\Git>where dnvm
C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
C:\Users\tdu\.dnx\bin\dnvm.cmd

I am assuming the first was by Visual Studio install, the second by the latest upgrade. The Visual Studio version does not have the unstable, so it fails.

**Comment by GuardRex** [comment]
This is a bad user experience. I just went Win10 preview with a new install of VS. The flavor of dnvm that ended up in both Microsoft DNX and .dnx were the same version that doesn't support unstable or update-self. Are we supposed to delete these versions and use PS to get the "developer" version of dnvm, or what?
