### ISSUE TITLE
dnvm upgrade install beta4 version instead of beta5 after install VS2015RC

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnvm#259]
Porting from 

From @cuiliang
>There seems VS2015RC installed another dnx in different location.
where dnvm
C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
C:\Users\Leal\.dnx\bin\dnvm.cmd

>when run dnvm upgrade, the command will set beta4 version of clr to default.
C:\Users\Leal
λ dnvm upgrade
Determining latest version
'dnx-clr-win-x86.1.0.0-beta4-11566' is already installed.
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta4-11566'

Comment from @mgravell

>I had this same conversation with David on jabbr last night! I am not qualified to say it is safe, but deleting the Program Files version worked for me, allowing the Users version to take over.

>There is a second problem here: the installer does not overwrite, so if you have had a previous version on your machine, the command [from here](https://github.com/aspnet/home) *will not overwrite* - so if you have beta4 installed; you currently need to manually delete the files from `%USERPROFILE%\.dnx\bin` in order to use the installer to get beta5.

>Suggestions for the installer:

>- it should overwrite the two files into `%USERPROFILE%\.dnx\bin`
>- if correct and possible (admin etc), it should delete the Program Files version completely

>Note: once you have beta5, `dnvm update-self` is a thing

**Comment by BrennanConroy** [comment]
```dnvm upgrade -u``` will give you beta5 versions of dnx, w/o -u you will get the stable versions

**Comment by cuiliang** [comment]
dnvm version problem resolved after using -u param.
Current problem is "VS2015RC installed another dnvm to windows Program Files folder".
This can also be resolved by removing  "C:\Program Files\Microsoft DNX\Dnvm\" manually.

**Comment by glennc** [comment]
Closing this one as it seems to be resolved. In the next version of VS we will not be putting DNVM on your path, instead you will need to use the developer command prompt or install it into your profile yourself. That should avoid the conflict there.
