### ISSUE TITLE
Bug in function Get-RuntimeName

### ISSUE THREAD

**Issue by IlyaGrebnov** [aspnet/dnvm#260]
Bug in function Get-RuntimeName

    if(Test-Path $aliasPath) {
        $BaseName = Get-Content $aliasPath

        $Architecture = GetArch $Architecture (Get-PackageArch $BaseName)
        $Runtime = GetRuntime $Runtime (Get-PackageArch $BaseName)
        $Version = Get-PackageVersion $BaseName
    }

I think

        $Runtime = GetRuntime $Runtime (Get-PackageArch $BaseName)

should be

        $Runtime = GetRuntime $Runtime (Get-PackageRuntime $BaseName)

**Comment by IlyaGrebnov** [comment]
In fact this is still broken I thin it should be just

    if(Test-Path $aliasPath) {
        $BaseName = Get-Content $aliasPath

        $Architecture = Get-PackageArch $BaseName
        $Runtime = Get-PackageRuntime $BaseName
        $Version = Get-PackageVersion $BaseName
    }

**Comment by BrennanConroy** [comment]
Same as #175
