### ISSUE TITLE
dnvm use latest

### ISSUE THREAD

**Issue by masaeedu** [aspnet/dnvm#263]
When using `dnvm use`, it might be useful to allow version resolution from friendly aliases such as "latest" or allow wildcards such as 1.0.\* in version strings, which will resolve to the latest matching version. Analogous wildcarding could also be implemented for the other commands.

It would be nice to not have to copy paste the version string from `dnvm list` when switching to the only coreclr/clr/mono runtime I have installed.

**Comment by davidfowl** [comment]
sounds like it would be a great pull request :smile:.

**Comment by masaeedu** [comment]
@davidfowl Alright then, I'll see what I can do.

**Comment by glennc** [comment]
Another thing we talked about recently was having `dnvm use` show a list that you could navigate and pick from.
