### ISSUE TITLE
dnvm run should support specifying architecture and runtime

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnvm#265]
Would be useful to specify `dnvm run default -r CoreCLR ...`. Unless I'm missing something obvious, the only way to achieve this today is by creating a new alias.

**Comment by dougbu** [comment]
This now works on Windows but not Linux / OSX.

**Comment by BrennanConroy** [comment]
69bc83e9797b0b3fa34d7afc84628f00aea62b5d
