### ISSUE TITLE
dnvm install for core clr opens a new window for cross gen - need a way to disable it

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnvm#266]
I am making a change in VS to call dnvm to install to install the dnx sdk and while I am testing my changes, I see that dnvm install for core clr is opening a new command window for showing cross gen output.

I need a way not to show it because it's an odd experience for VS.

This is blocking my checkin - so I definitely need this sooner (within a day or two would be good).

**Comment by BrennanConroy** [comment]
I thought dnvm stopped opening new windows a few months ago

**Comment by PradeepKadubandi** [comment]
@glennc , Do you know for sure if this is already fixed? The version currently chained into WTE does not at least behave that way.

Can we expedite a fix if it's not done?

**Comment by PradeepKadubandi** [comment]
Hmm, it seems when I got the latest dev version of dnvm scripts, this issue does not happen... so I think it may have been fixed but the version in WTE did not yet have the fix...

**Comment by glennc** [comment]
When did WTE last take DNVM? This is fixed now, as you saw, but I don't know when it was last updated.
