### ISSUE TITLE
"dnvm use <alias>" on Windows always installs dnx-clr even the alias contains dnx-coreclr

### ISSUE THREAD

**Issue by ChengTian** [aspnet/dnvm#268]
Reported by @rkeithhill 

On Linux I can use dnvm use latest and it will work correctly.  On Windows, dnvm use latest will failure saying it can't find dnx-clr-win-x86.1.0.0-beta5-11781.  When I create the alias I specify the runtime as coreclr.  Heck, the file ~\.dnx\alias\latest.txt contains:

dnx-coreclr-win-x86.1.0.0-beta5-11781

So why do I need to specify -r coreclr with dnvm use latest to make it work on Windows?

**Comment by glennc** [comment]
I think this will be fixed by the upcoming PR for supporting non-windows dnx. I will reference this in the PR if it does.

**Comment by Tratcher** [comment]
Yes, this appears to be fixed now.
