### ISSUE TITLE
Add a way to `dnvm use` the version specified in global.json for a project 

### ISSUE THREAD

**Issue by danroth27** [aspnet/dnvm#271]
When you run from the command line you get the currently active version on dnx. However this often results in you using a DNX version that is not compatible with the DNX and package versions needed for a specific project. You can specify which DNX version your solution needs in global.json. We should provide a simple way to `dnvm use` the version specified in global.json.

**Comment by natemcmaster** [comment]
:+1: for using the `global.json` files. 

Of course, this reminds me a lot of RVM and gemsets, which have their own problems <sup>[1](http://devblog.avdi.org/2015/08/11/what-its-like-to-come-back-to-a-ruby-project-after-6-months/)</sup>
