### ISSUE TITLE
"dnvm use" fails when Users folder has a space.  (1.0.0-beta4-10356)

### ISSUE THREAD

**Issue by rongriffin** [aspnet/dnvm#272]
I'm using 1.0.0-beta4-10356 of dnvm.  My user folder is c:\Users\Ron Griffin\ and when I run dnvm use to switch runtimes, I get an error due to the space in my user folder. 

![dnvmerror](https://cloud.githubusercontent.com/assets/1842859/7740832/ccb56a46-ff3c-11e4-9f90-1120cad19190.PNG)

A subsequent "dnvm list" shows the original runtime is still selected and not the version that I want to use.

**Comment by ircnelson** [comment]
My friend has the same problem, but the problem is that your name contains special chars...

**Comment by glennc** [comment]
This should be fixed in newer versions of dnvm, see https://github.com/aspnet/dnvm/pull/224. There are several closed issues referencing the same problem. Does your dnvm have the command `dnvm update-self`?

**Comment by rongriffin** [comment]
I updated and this is fixed for me.  Thanks.

**Comment by glennc** [comment]
No problem, glad it was an easy fix :). @ircnelson is there an issue for your friend with the special characters?

**Comment by eloekset** [comment]
@glennc I've got a special character "å" in my home folder path: C:\Users\EivindGussiås\ and using "dnvm use 1.0.0-beta5" added a path starting like C:\Users\EivindGussi?s\ to my PATH variable. Using "dnvm list", default was still set to 1.0.0-beta4. I manually set my PATH variable to C:\Users\EivindGussiås\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin and now "dnvm list" shows that 1.0.0-beta5 is default.

**Comment by glennc** [comment]
Ok, thanks @eloekset. Can you create a new bug for this? Make sure it has what version of DNVM you are using, in fact try and make sure it's the latest one :).

**Comment by eloekset** [comment]
Sorry for late response. I've downloaded the latest version of DNVM, which currently is 1.0.0-beta8-15502. Switching between DNX 1.0.0-beta5 and 1.0.0-beta6 works fine even with the special character "å" in my home folder path, so this issue has already been fixed.
