### ISSUE TITLE
dnvm upgrade fails....

### ISSUE THREAD

**Issue by Ncage1974** [aspnet/dnvm#277]
When i try to upgrade to the latest runtime i get the following error:

C:\Program Files (x86)\Microsoft Visual Studio 14.0>dnvm upgrade -r coreclr -arch x64
Determining latest version
Downloading dnx-coreclr-win-x64.1.0.0-beta5-11911 from https://www.myget.org/F/aspnetrelease/api/v2
Installing to C:\Users\john.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta5-11911
Adding C:\Users\john.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta5-11911\bin to process PATH
Adding C:\Users\john.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta5-11911\bin to user PATH
Compiling native images for dnx-coreclr-win-x64.1.0.0-beta5-11911 to improve startup performance...
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:186
- ... nvvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade  ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dnvm.ps1

The dnvm folder exist so i decided if i could use it anyways in visual studio. This is what happens when i try to run the project: 

![image](https://cloud.githubusercontent.com/assets/1213549/7870775/fc242c62-0550-11e5-93f5-ea9fce0350c4.png)

I tried to delete C:\Users\john.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta5-11911 folder and run the upgrade process again "thinking it was a fluke it failed". But the same thing.

**Comment by glennc** [comment]
The dialog is looking for a 32bit version of coreclr (x86) and you are installing x64. I suspect that it would've worked even with the error, since it appears the error is happening after that.

The reason for the error, I think, is that we renamed the native image generation command and your dnvm hasn't been updated. You can run `dnvm upgrade -r coreclr -arch x64 -nonative` to skip the native generation and avoid the problem for now.

If your dnvm is new enough to have the update-self command then you can run that, otherwise go and re-run the dnvm install commands from the home repo instructions to fix it.

**Comment by Ncage1974** [comment]
Hi Glen, and thanks for the response. It was weird your the one that responded because it was the reason i was messing with upgrading is because i was watching your video from ignite :). Anyways as you suggested adding the '-nonative' fixed the error i was getting while trying to upgrade with powershell but i'm still getting the dialog when i'm trying to run though video studio (IIS)? Do you know why its looking for the 'x86' version. I specified the 'x64' version in Application Tab and Debug tab in the project properties. When i try to run the project through visual studio. I immediately get the dialog and it doesn't get any further.

I'm running the RC of visual studio 2015. My DNVM version is: v1.0.0-beta4-10356. Is there an easy way to upgrade DNVM?

**Comment by glennc** [comment]
Hey @Ncage1974, took me a while to get back to this (sorry about that). Do you still see this? dnvm update-self will update DNVM for you.
