### ISSUE TITLE
Unable to call DNVM from msysgit bash on Windows

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/dnvm#280]
I'm running a bash terminal via cmder on Windows and am unable to call the dnvm installed by default with visual studio.

It appears to only be shipping with a `ps1` and `cmd` scripts?

**Comment by muratg** [comment]
Yes, this is not a tested scenario.  You can copy the bash file locally to see if it works, but I'm not sure how msysgit would be in general.

I assume cmd script works in this case?

**Comment by atrauzzi** [comment]
That's not a workaround, that's just "not supported".  I'm using bash because cmd and PS are insufficient.

:stuck_out_tongue_winking_eye:

**Comment by glennc** [comment]
Yeah, unfortunately the cmd file is broken and the bash file wouldn't do what you wanted even if you got it on the machine. Looks like you can't source it, and if you could it can't really install a windows dnx yet.

Not against making this work if there is a good way to do it, just not something we had tried yet.

**Comment by atrauzzi** [comment]
If things are shaping up the way I think they are for Windows 10, then there is still going to be a real need to run some kind of Unix compatibility layer.  Be it cygwin or msys.

My hope is that I can simply switch to using the msys bash with cmder.

**Comment by CoreyKaylor** [comment]
Yeah, it's unfortunate this isn't a higher priority. Most of our team's time is in git bash due to the similarity when jumping between OS's.

**Comment by CoreyKaylor** [comment]
I guess though it's not the end of the world to jump between them with "cmd" -> "exit" either.

**Comment by atrauzzi** [comment]
This is one in a growing list of reasons why people should keep bash in mind, even on Windows.  msys, msys2 and any that might come in the future won't be going away.  No matter how much work is put into PowerShell.

**Comment by muratg** [comment]
@CoreyKaylor, @atrauzzi In RC2, we're moving away from dnx, dnvm and dnu to the new [dotnet CLI](https://github.com/dotnet/cli) so almost all of these bugs will be closed once that work is complete.

([Roadmap](https://github.com/aspnet/Home/wiki/Roadmap))
