### ISSUE TITLE
dnvm does not work on windows 7

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnvm#281]
dnvm fails to install dnx on windows 7 (because of incompatible powershell version).

I tried removing the #requires at the top of the script on the machine and it fails with errors when I tried to run. [So the script code actually needs changes , it's not as trivial as removing the requires directive]

**Comment by muratg** [comment]
Yup, @glennc was also looking into this.  We need to decide what we need for beta5. 

Just asking customers on Win 7 to install a newer Powershell could be OK for Beta5.  We should make sure that Win 7 setup experience should be smooth though, and the inbox DNX should just work.  

cc @davidfowl @DamianEdwards
