### ISSUE TITLE
Need a way to know dnvm install succeeded

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnvm#284]
I talked to Andrew and Glenn about this.

Since VS used dnvm to install dnx, if for some reason  dnvm fails to install the dnx, VS reattempting to install again would not work because the folder already exists.

The proposal was to write some file towards the end of dnvm installation to indicate dnvm completed successfully and VS can use this to detect whether dnvm install succeeded or not to force install dnx.

This is needed for beta5 because today if dnvm fails for some reason, user has to know and manually go and delete the dnx folder so that VS will attempt to install it again.

**Comment by davidfowl** [comment]
Exit code not good enough?

**Comment by glennc** [comment]
The problem is really that the folder is left behind. Right?
