### ISSUE TITLE
Error when running dnvm update-self

### ISSUE THREAD

**Issue by glennc** [aspnet/dnvm#286]
#Moved from: https://github.com/aspnet/dnx/issues/2018

When I run dnvm update-self I get the error below.
```
Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
dnvm-update-self : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1:1431 char:9
+         & "dnvm-$cmd" @cmdargs
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dnvm-update-self], MethodInvocationException
    + FullyQualifiedErrorId : WebException,dnvm-update-self
```
I've seen this error when DownloadFile is called and the directory for the destination has not been created.

@sayedihashimi

**Comment by glennc** [comment]
What's your Powershell version?

Is it consistent, i.e. not because of an intermittent network problem?

**Comment by sayedihashimi** [comment]
I was running on windows 10. After running ```dnvm upgrade``` I'm not seeing it anymore.

**Comment by glennc** [comment]
dnvm upgrade and dnvm update-self are completely unrelated. I suspect the cause was some sort of network timeout or disconnect somewhere.

Come back on and re-open this if you manage to hit on it again, or find a reliable repro.

**Comment by sayedihashimi** [comment]
Ok sounds good thanks

**Comment by colepanike** [comment]
I get this error when I run in normal command line. I had to run in powershell. Just a note for anyone else who finds this like I did.

**Comment by beppler** [comment]
Hi I have the same problem here. Every time i ry to execute dnvm upgrade-self.

    Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
    dnvm-update-self : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
    At C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1:1453 char:13
    +             & "dnvm-$cmd" @cmdargs
    +             ~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [dnvm-update-self], MethodInvocationException
        + FullyQualifiedErrorId : WebException,dnvm-update-self

windows version 8.1
dnvm version v1.0.0-beta5
powershel version 4.0

**Comment by beppler** [comment]
Running Get-Command-Definition dnvm I got this:
    C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
    C:\Users\carlos.beppler\.dnx\bin\dnvm.cmd

The previous per-user version of dnvm is not the default one anymore.

Visual Studio 2015 installed a new dnvm.ps1 on "C:\Program Files\Microsoft DNX\Dnvm\". 

So to update this version of dnvm you must run your powershell or command prompt as administrator.

**Comment by beppler** [comment]
I think the problem is that Visual Studio 2015 instalation adds the following entries to the System Path:

    %USERPROFILE%\.dnx\bin
    C:\Program Files\Microsoft DNX\Dnvm\    

On my machine it is resolved to:

    C:\Windows\system32\config\systemprofile\.dnx\bin
    C:\Program Files\Microsoft DNX\Dnvm\

Those folders appears before the real path of dnvm on my user profile.

Then the dnvm-update-self command tries to update the file on `C:\Program Files\Microsoft DNX\Dnvm\` not the file on `.dnx` folder on my user profile.

**Comment by damtur** [comment]
The problem might be old outdated version. CMD and Powershell might use different dnvm versions.
To fix that run
`dnvm setup`

**Comment by Abdullah2993** [comment]
Run the power shell as Administrator.

**Comment by dime2lo** [comment]
So, I'm getting the same error. Already tried to Run Powershell as Administrator and tried to use "dnvm setup" too. 

Windows 8.1 Pro
.NET Version Manager v1.0.0-beta5-10384
Powershell 4.0

**Comment by genereux** [comment]
@dime2lo 

Try to restart the Powershell after the dnvm setup

**Comment by glennc** [comment]
It's also entirely possible that the beta5 version has some bugs. It might best to go re-run the setup script to re-download it. Then try update-self after that.

**Comment by punitganshani** [comment]
For me it worked by running following commands in PowerShell console

```
dnvm upgrade
dnvm update-self
```

**Comment by nelsonmorais** [comment]
With:
Windows 10
dnvm version v1.0.0-beta5-10384 installed

Running:
dnvm upgrade
dnvm setup
dnvm update-self

worked for me.

**Comment by uli-weltersbach** [comment]
Running in PowerShell rather than "regular" command line solved it for me as well.

**Comment by chrishaly** [comment]
run cmmand line as Administrator then execute "dnvm update-self" is ok

**Comment by craig-wagner** [comment]
I was getting this error as well. Running the command prompt as administrator fixed it. I _did not_ have to use a PowerShell prompt.

**Comment by Spongman** [comment]
got this error too. running from elevated prompt works, running from non-admin prompt crashes.

running from powershell makes no difference.
running upgrade/setup beforehand makes no difference.

.NET Version Manager v1.0.0-beta5-10384

```
C:\>where dnvm.*
C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1.bak
C:\Users\Me\.dnx\bin\dnvm.cmd
C:\Users\Me\.dnx\bin\dnvm.ps1
```

the above is the same for both elevated & non-elevated prompts.

---

ok, it looks like there error is here:

```
    $tempDnvmFile = Join-Path $CurrentScriptRoot "temp"
    ...
    $wc.DownloadFile($DNVMUpgradeUrl, $tempDnvmFile)
```

it's trying to download the temporary file into the `C:\Program Files` directory.

it needs to check that it has access to do this and show a more intelligible error.

**Comment by oswaldofreitas** [comment]
@damtur solution worked for me.

dnvm setup

**Comment by LeeCampbell** [comment]
```
dnvm upgrade
dnvm setup
dnvm update-self
```

Worked for me too.

**Comment by talk2sunil83** [comment]
Running in elevated PowerShell rather than "regular" command line solved it for me as well.

**Comment by ropstah** [comment]
I just tried command prompt and Powershell in both elevated as well as normal mode. I tried:

`dnvm upgrade
dnvm setup
dnvm update-self`

all give the same error: 

`& : The term 'C:\Users\R.dnx\bin\dnvm.ps1' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the n
ame, or if a path was included, verify that the path is correct and try again.
At line:1 char:180
- ... envvars.cmd';& 'C:\Users\R.dnx\bin\dnvm.ps1' update-self
-                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\Users\R.dnx\bin\dnvm.ps1:St
    ring) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException`

I tried repairing and uninstalling/installing. But the commands still don't work and the dnvm.ps1 file also still doesn't exist.

**Comment by BrennanConroy** [comment]
Well if dnvm doesn't exist you should probably install it. https://github.com/aspnet/Home/blob/dev/dnvminstall.ps1

**Comment by kirodge** [comment]
`dnvm update-self`
 fails if there is already a folder named **temp** in the .dnx\bin\ folder:

```
Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
dnvm-update-self : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient req
uest."
At line:1 char:1
+ dnvm-update-self
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dnvm-update-self], MethodInvocationException
    + FullyQualifiedErrorId : WebException,dnvm-update-self
```

but works if I remove the temp folder
`Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1`
