### ISSUE TITLE
dnvm upgrade - Exception calling ".ctor" Invalid Uri

### ISSUE THREAD

**Issue by Conrad2134** [aspnet/dnvm#289]
When trying to run dnvm upgrade, I get this exception:

![capture](https://cloud.githubusercontent.com/assets/3484188/8046514/210ae7ce-0e01-11e5-8399-f69b9b8d5ff6.PNG)

I am running Win 7 Enterprise w/ Powershell 4.0

**Comment by Conrad2134** [comment]
I've been debugging through the script and found that it errs out on this line on the apply-proxy method:

$wp = New-Object System.Net.WebProxy($Proxy)

**Comment by Conrad2134** [comment]
I took out my username + password out of the proxy url in my user variables, and it ran successfully. It was looking like this:

http://USERNAME:PASSWORD@ADDRESS:80  - and I changed it to look like:
http://ADDRESS:80 - which made it work. 

I did have an '@' in my password - could it not have liked parsing that, expecting an @ to delimit the password and address? I don't know much about proxies and such.

**Comment by ankeshdave** [comment]
@Conrad2134 
If your network is using 'NTLM' proxy then on `Windows` you need not specify Username and Password. Most application on windows pick up proxy from 
```
IE (IE Options -> Connection -> Lan Settings)
```
If you still need to use proxy (with uname & pass) for some applications (Like npm ( in .npmrc file) or for bower (in .bowerrc file)) you can use an Authentication Proxy like [CNTLM] (http://cntlm.sourceforge.net/)  
I use this in my network, Also you can use the same Linux (Ubuntu, CentOS tested) :smile:

**Comment by Conrad2134** [comment]
Thank you @ankeshdave! We do need proxy for some stuff, so I will look into CNTLM.
