### ISSUE TITLE
Powershell error after running DNVM

### ISSUE THREAD

**Issue by flipdoubt** [aspnet/dnvm#292]
I followed [these instructions](http://typecastexception.com/post/2015/05/17/DNVM-DNX-and-DNU-Understanding-the-ASPNET-5-Runtime-Options.aspx#Getting-Started---Installing-DNVM) to install DNVM using the following CMD script:

> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

Now, running "DNVM" produces the following error output:

```
C:\Users\DaveS.BrettMc-PC>dnvm
You must specify a command!
   ___  _  ___   ____  ___
  / _ \/ |/ / | / /  |/  /
 / // /    /| |/ / /|_/ /
/____/_/|_/ |___/_/  /_/
.NET Version Manager v1.0.0-beta6-10383
By Microsoft Open Technologies, Inc.
usage: dnvm <command> [<arguments...>]

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>

commands:
ForEach-Object : A parameter cannot be found that matches parameter name 'ShowW
indow'.
At C:\Users\DaveS.BrettMc-PC\.dnx\bin\dnvm.ps1:835 char:27
+             ForEach-Object <<<<  {
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], Parameter
   BindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
   ands.ForEachObjectCommand
```

So ... here are my questions:
1. What happened?
2. Is there a fix?
3. Can I uninstall and reinstall using a different URL? If yes, how do I uninstall and what is the URL?

**Comment by DamianEdwards** [comment]
Attendees of our workshop here at NDC Oslo ran into this as well, but only when on Windows 7. Updating to PowerShell 3.0 fixed the issue.
