### ISSUE TITLE
dnvm.sh marked as an executable but could not be run by the operating system

### ISSUE THREAD

**Issue by duluca** [aspnet/dnvm#296]
I've installed `dnvm` using `brew` on Mac.

However, after install, `source dnvm.sh` returns `No such file or directory found.`

After specifying the path to it like `source /usr/local/bin/dnvm.sh` then I get pages and pages of errors, which starts like: 
    Illegal command name '[[ "$_DNVM_BUILDNUMBER" = {{* ]]'
    /usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh (line 35): [[ "$_DNVM_BUILDNUMBER" = {{* ]] && _DNVM_BUILDNUMBER="HEAD"
                                                                ^
    in . (source) call of file '/usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh',    
	called on standard input,

    fish: Expected a command name, got token of type 'Run job in background'. Did you mean 'COMMAND; and COMMAND'? See the help section for the 'and' builtin command by typing 'help and'.
    /usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh (line 35): [[ "$_DNVM_BUILDNUMBER" = {{* ]] && _DNVM_BUILDNUMBER="HEAD"

When I directly try to run `/usr/local/bin/dnvm.sh`, then I get `dnvm.sh marked as an executable but could not be run by the operating system`.

**Comment by radnor** [comment]
It appears you're using `fish` as a shell. The `/usr/local/bin/dmvm.sh` script is designed to be used by a Bourne shell like `bash` or even `zsh`, so in order to use dmvm you will have to stop using `fish`.

**Comment by duluca** [comment]
Switched to `zsh` it works now. Thanks.
