### ISSUE TITLE
dnvm adds an alias for delete option

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnvm#306]
```
PS C:\source\dnx> dnvm alias -d beta 4
Setting alias 'beta' to 'dnx-clr-win-x86.4'
```

Note there is no error even though the runtime it tried to alias 'dnx-clr-win-x86.4' did not exist

**Comment by Tratcher** [comment]
Why is there a space in the alias name?

This appears to be working for with beta8.

**Comment by moozzyk** [comment]
There is no space in the alias name - when I look at help it would be the version. The paradox here is that you are trying to delete an alias for non-existing version and instead a new alias is (was?) created.

**Comment by Tratcher** [comment]
Nevermind, this is still broken
```
C:\git\Universe\HttpAbstractions>dnvm alias

Alias   Name                                     Orphan
-----   ----                                     ------
default dnx-clr-win-x86.1.0.0-beta8-15120         False
mac     dnx-coreclr-darwin-x64.1.0.0-beta8-15120  False

C:\git\Universe\HttpAbstractions>dnvm alias -d mac 1
Updating alias 'mac' to 'dnx-clr-win-x86.1'
```

-d appears to have lower priority than updating an existing alias version.
