### ISSUE TITLE
dnvm alias doesn't check for existence of runtime resulting in bad error case.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/dnvm#313]
DNVM alias doesn't do enough when creating alias' resulting in potentially difficult to get out of scenarios for unintentional actions. The following scenario gets you into a state where you can't use your aliased runtimes:
1. Delete all alias files in your `.dnx/alias` directory.
2. Install a runtime to alias (`dnvm install 1.0.0-beta5`)
3. Type `dnvm alias 1.0.0-beta5 default` - This is wrong but I've found myself mixing up the order on a few occasions. Ultimately you get: `Setting alias '1.0.0-beta5' to 'default'.`
4. You've now realized you made the mistake of mis-ordering your alias command so you type: `dnvm alias default 1.0.0-beta5`. Which then yields you: `Setting alias 'default' to '1.0.0-beta5'.`
5. By now you feel like you're in a correct state after a simple error. Type `dnvm use 1.0.0-beta5`. You get: 
   ![image](https://cloud.githubusercontent.com/assets/2008729/8244103/15285710-15d2-11e5-8e2f-04daa7066b47.png)
   Typing dnvm use default yields a similar error.

The only way I've found to get around this error is to delete the `.dnx/alias` files directly.

One last note is that when you do `dnvm list` it doesn't show either alias.

**Comment by moozzyk** [comment]
Another related issue then #311 - if we did not use positional parameters it would be hard(er) to `mix up the order`
