### ISSUE TITLE
kvm commands showing Usage exits with code=0

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/dnvm#32]
If I leave required parameters out for kvm commands, it shows the USAGE string and terminates with return code 0, indicating success.

However by convention, command line programs terminating with insufficient parameters and thus showing the error message exit with non-zero exit codes, like 1. `curl`, `git`, `gem` are some examples. My 2 cents.

**Comment by muratg** [comment]
Good suggestion. .ps1 already has the correct behavior, but .sh seems to return 0 for the error cases.
