### ISSUE TITLE
dnvm exec/dnvm run require aliasing

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnvm#326]
dnvm `exec` and `run` commands take `<VersionOrAlias>` argument:

```
dnvm exec <VersionOrAlias> [<Command>] [<Arguments>]
dnvm run <VersionOrAlias> [<DnxArguments>]
```

However it is impossible to specify runtime or architecture. As a result if the user really wants to use a specific runtime they need to create an alias which should not be needed and is inconsistent with other commands.

**Comment by dougbu** [comment]
+1 just hit this issue attempting to make `_k.shade` able to switch runtimes on Linux. Have `-arch` and `-r` parameters for `dnvm exec` and `dnvm run` on Windows but not Linux.

**Comment by dougbu** [comment]
@moozzyk I just tried to reproduce this issue on Linux and Windows. Looks like it's fixed. Do you agree?

**Comment by moozzyk** [comment]
Yes. The commands themselves work. However on Windows help does not show descriptions:

```
usage:
  dnvm exec <VersionOrAlias> [<Command>] [-arch <Architecture>] [-r <Runtime>] [<Arguments>]

options:
  <VersionOrAlias>     The version of alias of the runtime to make active in the sub-shell
  <Command>            The command to execute in the sub-shell
  -arch
  -r
  <Arguments>
```

On linux these parameters are not even in the help:

```
dnvm exec <semver>|<alias> <command> <args...> 
  <semver>|<alias>            the version or alias to execute in
  <command>                   the command to run
  <args...>                   arguments to be passed to the command
```

(compare with `dnvm use`).

**Comment by dougbu** [comment]
@moozzyk FYI fixes to the `dnvm.sh` help from @yaakov-h and to the `dnvm.ps1` help from me are in #455. In particular, I fixed the `dnvm exec` and `dnvm run` help on Windows yesterday. Will push soon.

**Comment by moozzyk** [comment]
:+1:
