### ISSUE TITLE
[Linux] `dnvm upgrade -arch x86` ignores the architecture specification

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnvm#331]
When installing or upgrading a runtime, the architecture is consistently ignored on Linux. There's one mono runtime (x86 perhaps?) and only one coreclr runtime can be installed (x64 on the machine I was using).

This command-line argument should be removed.

**Comment by dougbu** [comment]
This issue may become moot if we fix #332.

**Comment by muratg** [comment]
Looks like @332 is fixed. So is this one good to close @dougbu?

**Comment by dougbu** [comment]
Yup, no reason to remove `-arch` now.
