### ISSUE TITLE
"dnu: Permission denied" on mac

### ISSUE THREAD

**Issue by cnblogs-dudu** [aspnet/dnvm#335]
Run dnu after `dnvm upgrade -u` on mac, get the following error:
> -bash: ~/.dnx/runtimes/dnx-mono.1.0.0-beta6-12114/bin/dnu: Permission denied

Then `ls -l dnu`:
> -rw-r--r--  1 user staff  539 Jun 23 00:21 dnu

Then `chmod +x dnu` and fixed.

**Comment by davidfowl** [comment]
Update dnvm and it'll work
