### ISSUE TITLE
fresh dnvm install windows 7 has difficulty doing it's job because of folder permissions #680

### ISSUE THREAD

**Issue by fir3pho3nixx** [aspnet/dnvm#336]
Hi 

I tried installing this on windows(without Visual Studio) using the following powershell script: 

    @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

My paths all appeared to come out fine. I could run

    dnvm help 

and it would return the help screen. However when I ran 

    dnvm list

The list was always empty. So then I tried 

    dnvm upgrade

and this appeared to download the beta binary `dnx-clr-win-x86.1.0.0-beta4` to `temp` folder in my users profile but failed because of folder permissions. See below:

    Move-Item : Access to the path 'C:\Users\Gavin\.dnx\runtimes\temp\dnx-clr-win-x86.1.0.0-beta4' is denied.

Once I correct permissions to the `temp` folder everything started working again. I made sure I ran the scripts in shell windows with admin privileges. You guys getting this on later versions of windows?

**Comment by glennc** [comment]
@fir3pho3nixx Is this still an issue? We've done some work in this area so I am hoping it is already fixed in newer versions of DNVM.

**Comment by fir3pho3nixx** [comment]
Alas, I took the windows 10 update and can no longer replicate. Happy to close :)

**Comment by glennc** [comment]
Closing then. If someone else finds this and still has the issue then jump in and let us know.

**Comment by spooti** [comment]
I'm having similar issue on Win10 with fresh install of vs2015 community and asp.net 5
`C:\WINDOWS\system32>dnvm install 1.0.0-rc1-update1
Downloading dnx-clr-win-x86.1.0.0-rc1-update1 from https://www.nuget.org/api/v2
Installing to C:\Users\myuser\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1
Move-Item : Access to the path 'C:\Users\myuser\.dnx\runtimes\temp\' is denied.
`
please advice
