### ISSUE TITLE
dnvm don't recognize -u option.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/dnvm#339]
As mention here http://dotnet.github.io/core/getting-started , I use this command 
dnvm install -r coreclr latest -u
but result is the following error in Power Shell 3.
A parameter cannot be found that matches parameter name 'u'.

thanks to help

**Comment by BrennanConroy** [comment]
What version of dnvm do you have? Try dnvm update-self to get the latest, or if you have a really old version, reinstall dnvm.

**Comment by muratg** [comment]
Yup, looks like you're using an old version of dnvm.  Please reopen if you're hitting the issue with the current dnvm.
