### ISSUE TITLE
Ability to display active runtime

### ISSUE THREAD

**Issue by arthrp** [aspnet/dnvm#342]
It would be great if user could get currently active runtime. E.g. `dnvm list --active` or `dnvm active` which would produce something like 

```
Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----   
  *    1.0.0-beta6-12108    coreclr x64  ~/.dnx/runtimes      
```

Although, I would prefer CSV, for easy parsing:

```
1.0.0-beta6-12108,coreclr,x64,~/.dnx/runtimes
```

This would be _really_ handy for various scripts. Because current output of `dnvm list` is not really machine-readable.

**Comment by Eilon** [comment]
BTW on Windows `dnvm` is a PowerShell script, which is very machine readable because it's all programmatic. You can pipe the output as a .NET object and format it in other ways.

**Comment by arthur-peka** [comment]
Ok, but do you consider Unix-like systems as second-class citizens? :)

**Comment by Eilon** [comment]
No, just saying that on some platforms there are some extra neat tricks!

I'm wondering if you can elaborate on the need for this - is there something in particular you're trying to script?

**Comment by arthur-peka** [comment]
I intend to use it in yeoman generator for .NET Core (https://github.com/arthur-peka/generator-dotnetcore) to provide specific instructions to user (NuGet works with mono runtimes only at moment). But I guess the details don't matter?

**Comment by Eilon** [comment]
I think understanding the scenarios can be helpful... because suppose it had an option to output as a CSV, now there's another problem: you need to parse the CSV :smile: I wonder if instead there were simple programmatic ways to get at the data you want, and then you could consume them in a more direct manner. E.g. have a `Microsoft.Dnx.RuntimeUtils::GetActiveRuntime() --> string` or something.

**Comment by arthur-peka** [comment]
Parsing CSV in _this_ case should be easy as csvString.split(",") or similar.

**Comment by Eilon** [comment]
Ah, that would depend on whether the columns have "headers" though. Please note that we've changed the order of parameters before, though it's perhaps unlikely that we'll change it again.

**Comment by mholo65** [comment]
Does it really need to be CSV? Can't you just split by whitespace or grep the wanted data?

**Comment by arthur-peka** [comment]
@mholo65 
>Because current output of dnvm list is not really machine-readable.

That is the main point.

**Comment by mholo65** [comment]
But, as easy as you could split by e.g. comma, you could also split by white-space.

From [String.Split Method (Char[]) on MSDN](https://msdn.microsoft.com/en-us/library/b873y76a.aspx)
```
If the separator argument is null or contains no characters, 
the method treats white-space characters as the delimiters
```

This would make ```string.split(null)``` equal to ```string.split(',')``` as if it where comma-separated.

Or, as I mentioned. You could always use regex to find wanted data.

**Comment by arthur-peka** [comment]
@mholo65 I think discussion (explanation, really) about why standards are better than ad-hoc is out of scope of this issue.
