### ISSUE TITLE
Consider running mono --aot on install

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnvm#345]
Takes a while and only does individual assemblies but it seems like it speeds roslyn up a bit /cc @migueldeicaza

**Comment by muratg** [comment]
cc: @glennc

**Comment by borgdylan** [comment]
This is ideal to do. It's mono's equivalent of running ngen.

**Comment by glennc** [comment]
up-for-grabs?

**Comment by davidfowl** [comment]
Somebody needs to test it out end to end first. Last it tried it's *super* slow to run this and it doesn't do dependencies either.

**Comment by borgdylan** [comment]
You can call iit using wildcards iin a shell I.e it does many assemblies at once making a native image for each.
