### ISSUE TITLE
error to get beta5 on ubuntu

### ISSUE THREAD

**Issue by tempdata** [aspnet/dnvm#348]
Hi, I can download unstable coreclr versions but getting the following error for beta5 stable build. I am not behind proxy but running ubuntu as VM.

dnvm install latest -r coreclr -arch x64
Determining latest version
Error: Could not find latest version from feed https://www.nuget.org/api/v2

```
tempdata@ubuntuvm:~/Dev$ dnvm install latest
Determining latest version
Latest version is 1.0.0-beta5 
dnx-mono.1.0.0-beta5 already installed. 
Adding /home/tempdata/.dnx/runtimes/dnx-mono.1.0.0-beta5/bin to process PATH
tempdata@ubuntuvm:~/Dev$ dnvm install latest -r coreclr 
Determining latest version
Error: Could not find latest version from feed https://www.nuget.org/api/v2
tempdata@ubuntuvm:~/Dev$ dnvm install latest -r coreclr -arch x64 -u
Determining latest version
Latest version is 1.0.0-beta6-12189 
dnx-coreclr-linux-x64.1.0.0-beta6-12189 already installed. 
Adding /home/tempdata/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta6-12189/bin to process PATH
tempdata@ubuntuvm:~/Dev$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
       1.0.0-beta6-12189    mono         ~/.dnx/runtimes      
  *    1.0.0-beta6-12189    coreclr x64  ~/.dnx/runtimes      
       1.0.0-beta5          mono         ~/.dnx/runtimes      default

```

**Comment by BrennanConroy** [comment]
We aren't releasing non-windows coreclr dnx's currently, so you should only be able to play with the unstable ones of those.

**Comment by cheers00** [comment]
+ @davidfowl 
I am also seeing the above problem for all coreclr builds (stable and unstable). #238. But I am behind proxy.

@BrennanConroy the blog below seem to indicate that beta5 is available for Linux.
http://blogs.msdn.com/b/webdev/archive/2015/07/04/updates-to-asp-net-5-yeoman-generators-for-beta-5.aspx

**Comment by BrennanConroy** [comment]
You have to use DNX451, i.e. Mono on Linux

**Comment by jiangpeng311** [comment]
you can try beta6
```
$ dnvm upgrade -u -r coreclr
```
