### ISSUE TITLE
dnvm/dnu require 'CALL' to be used in script

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/dnvm#352]
Attempting to use the following script for our performance CI (command line step in TeamCity).

```
dnvm upgrade -runtime CLR -unstable
dnvm list
dnu restore
dnx . test
```

Only the first command actually gets run. You have to prefix everything with `call` in order to get things to run.

```
call dnvm upgrade -runtime CLR -unstable
call dnvm list
call dnu restore
dnx . test
```

**Comment by rowanmiller** [comment]
BTW this is presumably because dnu/dnvm are currently cmd files... but that is not very obvious

**Comment by leak** [comment]
Just stumbled across the very same issue and indeed it is very obscure.

TeamCity just exits the script cleanly after the first dn* command. Trying to run the script on console simply makes your whole console window disappear...

**Comment by Nekogdiuk** [comment]
Trying to prepare environment - for this goals i use ansible.
And have the same problem.
