### ISSUE TITLE
Deleting runtime with default alias breaks solution in Visual Studio

### ISSUE THREAD

**Issue by Ketrex** [aspnet/dnvm#353]
I upgraded to beta6 and reassigned the 'default' alias to beta6 as well.  I decided to downgrade from beta6 back to beta5 but I forgot to reassign the 'default' alias. Upon opening Visual Studio, I was presented with the error that the beta6 dnx runtime could not be found and none of my solution projects would build.

I was able to fix this by using dnvm and reassigning the 'default' alias to beta 5. My concern is that when presented with this error message in Visual Studio, there does not appear to be any way to fix the default alias from within the IDE.   Perhaps this error could be presented with a drop-down menu allowing the user to reassign the default alias, or at least some text explaining the importance of the default alias pointing to a valid runtime version.

**Comment by muratg** [comment]
@PradeepKadubandi @mayurid Can the tooling show a more friendly/actionable error in this case?  Something in the lines of "You don't have a default runtime, please set one using....."
