### ISSUE TITLE
suggestion: dnvm update available notification.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/dnvm#356]
After seeing lots of questions on jabbr about why something is not working being almost always an out of date dnvm, I think it will be great if dnvm tells when there's an available update something like

there's a dnvm update available. type dnvm update-self to update.

**Comment by mholo65** [comment]
Is there currently a better way to determine if there's a new version, than downloading dnvm.sh from aspnet/home and grepping version?

Even with a decent internet connection, the following command takes >300ms to execute, which IMO is too long (if check is done everytime dnvm command is executed):
```shell
curl -s $_DNVM_UPDATE_LOCATION | grep -Eo '^_DNVM_BUILDNUMBER=".+?"$' | cut -d\" -f2
```

**Comment by muratg** [comment]
Yeah, I don't think adding 300+ms to dnvm in each run is the right way to do this. Putting this in backlog to consider in the future.
