### ISSUE TITLE
dnvm install "1.0.0-beta6-12234" -unstable Fails, access denied to path

### ISSUE THREAD

**Issue by darrenscrine** [aspnet/dnvm#358]
Hi, trying to update DNVM and it fails with a access denied. I'm local admin, but still get this problem.

Move-Item : Access to the path 'C:\Users\darren.s.dnx\runtimes\temp\dnx-clr-win-x86.1.0.0-beta6-12234' is denied.

As a workaround I applied Everyone Full Control to the folder, still no better

any ideas?

Thanks

Darren

**Comment by spooti** [comment]
Having similar issue fresh install on win10 

> dnvm install latest
> Determining latest version
> Downloading dnx-clr-win-x86.1.0.0-rc1-update1 from https://www.nuget.org/api/v2
> Installing to C:\Users\myuser\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1
> Move-Item : Access to the path 'C:\Users\myuser\.dnx\runtimes\temp\' is denied.

**Comment by darrenscrine** [comment]
I got around it by manually copying all files in temp to its parent directory

**Comment by spooti** [comment]
Thanks, so just to be clear copy the files from temp to runtimes then run the dnvm install?

**Comment by darrenscrine** [comment]
Yep, worked for me. Temp just appears to be where it done loads to before moving to the runtimes folder, so it's just failing doing the move.

**Comment by spooti** [comment]
all I see in temp is folders and they are all empty

**Comment by rgudlooru** [comment]
I ran into the same error and got past it by closing VSCode. It somehow had a lock on the directory. In fact I could install as normal user, didn't have to do Run As Admin either.
