### ISSUE TITLE
kvm list 'Alias' column to be listed between Active and Version columns

### ISSUE THREAD

**Issue by Praburaj** [aspnet/dnvm#36]
Today kvm list shows `Alias` as the last column in the result. To associate an alias to a version of KRE there too much of eye ball movement from left to right of the screen as there is physical location in between these which can be bit longer strings. 

```
Active Version            Runtime Architecture Location                      Alias            
------ -------            ------- ------------ --------                      -----            
       1.0.0-alpha3-10156 svr50   x64          C:\Users\prabht\.kre\packages                  
       1.0.0-alpha3-10156 svrc50  x64          C:\Program Files\KRE\packages                  
  *    1.0.0-alpha3-10161 svr50   x86          C:\Users\prabht\.kre\packages fromnupkg1, test1
```
Ask: Put the `Alias` column between `Active` and `Version` fields.

**Comment by muratg** [comment]
See @lodejard's comment on #93.  Closing
