### ISSUE TITLE
Unable to install older dnvm betas in Linux

### ISSUE THREAD

**Issue by ganeshran** [aspnet/dnvm#362]
Hello,

I am trying to install beta4 to run Omnisharp-Roslyn but it gives a 400 bad request error.  Tried on both mono and clr. Also tried on Arch Linux and CentOS 7 to confirm it isn't a distro specific issue.

Also it creates the runtime directory which isn't deleted on failure. So the empty folder starts showing up in the dnvm list. 

Giving the output below. I have tested it with both beta4 and beta5. Also tried the format 1.0.0-beta4 and 1.0.0-beta5 with no luck. Is there a specific build number I have to use? 

>
ganesh@duraip-pc:~/Development/ASPNET/Home/samples/latest/HelloMvc|dev⚡
⇒  dnvm install beta4 -r coreclr -f
Forcing download by deleting /home/ganesh/.dnx/runtimes/dnx-coreclr-linux-x64.beta4 directory 
Downloading dnx-coreclr-linux-x64.beta4 from https://www.nuget.org/api/v2
Download: https://www.nuget.org/api/v2/package/dnx-coreclr-linux-x64/beta4
######################################################################## 100.0%
HTTP Error 400 fetching dnx-coreclr-linux-x64.beta4 from https://www.nuget.org/api/v2

**Comment by BrennanConroy** [comment]
Have you tried without -r coreclr? We haven't uploaded cross-plat coreclr dnx's to NuGet yet so this is the expected behavior.

**Comment by ganeshran** [comment]
Hi @BrennanConroy It works with mono as runtime. 

Should I close this issue as it's expected behavior?

**Comment by ganeshran** [comment]
One more possible bug is that when  I try to install the beta4 and it's not found (as in case of coreclr), the directory is created in .dnx/runtimes but when the install fails, it leaves the directory intact.

The next time I switch to that  binary using dvnm use,  it thinks that the runtime is present then complains of an error saying that bin folder is not present. I reckon that if the runtime install fails, then the cleanup script should delete the created directory too

**Comment by BrennanConroy** [comment]
Ya, it leaves behind a folder on bad installs, known issue, being tracked by some other bug.

**Comment by ganeshran** [comment]
Cool. Closing this issue as it's already tracked.

**Comment by ganeshran** [comment]
@BrennanConroy Does it mean that we can always install only the latest coreclr dnx version? 

I am trying to run omnisharp-vim with omnisharp-roslyn and that supports only beta4 of dnx.  With mono.

**Comment by BrennanConroy** [comment]
First off mono is not coreclr. So if you want you can easily get different versions of dnx mono by doing ```dnvm install <version>``` where ```<version>``` could be 1.0.0-beta4. Now if you want to use coreclr then you need to be using a NuGet feed that has the dnx coreclr runtimes. Currently we only push them to our dev feed, so if you want to grab those you will need to run ```dnvm install <version> -r coreclr -u```

**Comment by ganeshran** [comment]
Thanks Brennan, got it!

**Comment by ganeshran** [comment]
@BrennanConroy  Sorry for reopening this issue, but it still doesn't work. I tried it with the -u switch for both beta4 and 1.0.0-beta4. It gives an 404 error. It either requires a minor version or the packages are not up on the dev feed

Commands: 
dnvm install beta4 -r coreclr -u 
dnvm install 1.0.0-beta4 -r coreclr -u

Output
>
ganesh@localhost:~/Development/dotnet/omni/sample|
⇒  dnvm install beta4 -r coreclr -u                  
Downloading dnx-coreclr-linux-x64.beta4 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-coreclr-linux-x64/beta4
######################################################################## 100.0%
dnx-coreclr-linux-x64.beta4 was not found in repository https://www.myget.org/F/aspnetvnext/api/v2 
This is most likely caused by the feed not having the version that you typed. Check that you typed the right version and try again. Other possible causes are the feed doesn't have a DNX of the right name format or some other error caused a 404 on the server.
ganesh@localhost:~/Development/dotnet/omni/sample|
⇒  dnvm install 1.0.0-beta4 -r coreclr -u
Downloading dnx-coreclr-linux-x64.1.0.0-beta4 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-coreclr-linux-x64/1.0.0-beta4
######################################################################## 100.0%
dnx-coreclr-linux-x64.1.0.0-beta4 was not found in repository https://www.myget.org/F/aspnetvnext/api/v2 
This is most likely caused by the feed not having the version that you typed. Check that you typed the right version and try again. Other possible causes are the feed doesn't have a DNX of the right name format or some other error caused a 404 on the server.

**Comment by BrennanConroy** [comment]
That's because that version doesn't exist.
