### ISSUE TITLE
dnvm exec and run should support "based on current project/solution"

### ISSUE THREAD

**Issue by lodejard** [aspnet/dnvm#364]
Today it's `dnvm exec|run [versionOrAlias] ...`

We should add another keyword like `.` or `current` or `local` or `something` which would enable `dnvm exec something dnu restore`

Expectation would be it would hunt for global.json and use the sdk version from there. 

This would probably be what build scripts (like in kudu?) would then use, rather than call `dnvm use` before `dnu restore` and `dnu publish`

**Comment by jp311** [comment]
`dnvm exec [versionOrAlias] dnu` -> `dnvm util [versionOrAlias]`
