### ISSUE TITLE
dnvm.sh not working with fish shell

### ISSUE THREAD

**Issue by gblmarquez** [aspnet/dnvm#367]
I've installed dnvm using brew on Mac.

However, after install, source dnvm.sh returns No such file or directory found.

When I directly try to run /usr/local/bin/dnvm.sh, then I get dnvm.sh marked as an executable but could not be run by the operating system.

Then I just searched for this issue and I found this [https://github.com/aspnet/dnvm/issues/296](https://github.com/aspnet/dnvm/issues/296)

I think we need to keep tracking of this issue to future fixing.

Best regards,
Gabriel

**Comment by vmlf01** [comment]
The fish functions in this repo helped me: https://github.com/mgolisch/dnvm-fish

**Comment by gblmarquez** [comment]
Thanks @vmlf01!

**Comment by crazyDiamond** [comment]
This helped me as well. Thank you!
