### ISSUE TITLE
dnvm upgrade to beta6 leaves dnu without execute permissions on osx

### ISSUE THREAD

**Issue by dennisburton** [aspnet/dnvm#368]
After running dnvm upgrade on osx, dnu was correctly placed in the runtimes/[version]/bin directory but did not have execute permissions.

chmod +x dnu functions as a workaround.

**Comment by BrennanConroy** [comment]
What version of dnvm? Try dnvm update-self to get the latest version.

**Comment by dennisburton** [comment]
dnvm was on beta5 at the time of upgrade. Creating a PR for the dnvm.sh file to add the same code for dnu as exists for dnx at ~ line 252

**Comment by BrennanConroy** [comment]
6550ac887e623bf2b32c647814e67969e36cc1e1
