### ISSUE TITLE
VS2015RTM Tests: Unable to find the runtime installation directory for the source

### ISSUE THREAD

**Issue by karldodd** [aspnet/dnvm#371]
After upgrading from 2015 RC to RTM, we bumped into an error that no tests are shown in the VS test explorer windows with the following error:

```
------ Discover test started ------
Unable to find the runtime installation directory for the source: 'C:\repo\src\Solution\src\Project1.Testing\project.json'
Unable to find the runtime installation directory for the source: 'C:\repo\src\Solution\src\Project2.Testing\project.json'
========== Discover test finished: 0 found (0:00:00.5614723) ==========
```

Project.json content:

```
"dependencies": {
    "xunit": "2.1.0-*",
    "xunit.runner.dnx": "2.1.0-*",
    "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta5"
},
"commands": {
    "test": "xunit.runner.dnx"
},
"frameworks": {
    "dnx451": { } 
}
```

We are using DNX 1.0.0-beta5. Btw, the tests are successfully found and running fine under command line (i.e. by running dnx . test). Please advise. Thanks a lot.

**Comment by BrennanConroy** [comment]
This does not belong in the dnvm repo. Move to tooling or dnx.

**Comment by karldodd** [comment]
Thanks. Didn't know there is a aspnet/tooling repo.

Moved the issue here:
https://github.com/aspnet/Tooling/issues/122
