### ISSUE TITLE
DNVM breaks .profile on Linux

### ISSUE THREAD

**Issue by lgtelles** [aspnet/dnvm#376]
**Background**
I've stumbled in a issue when installing dnvm on my Linux Mint 17.2 .

As soon as i've installed it using the tutorials on the github, I've rebooted my machine and was unable to log in using X (Gnome).
Dug around, found an issue here in github (couldn't find it now) that was related to the line appended on .profile. Someone proposed there that it should be moved to .bashrc 

Then I've exchanged some tweets with @glennc, proceeded to make a pull request with a temporary workaround on the .md file to help other people stuck on this problem (https://github.com/aspnet/Home/pull/771) and dug a little more into the issue.

The root cause of this error is: The .profile gets run by Dash (POSIX BASH) instead of Bash. Why? Because on Gnome (/etc/gdm/XSession or /etc/mdm/XSession in Linux Mint) uses /bin/sh to run the startup scripts. And in some distros (Ubuntu and several others), the /bin/sh is symlinked to Dash instead of bash.

**Possible Solutions**
1. instead of putting the DNVM on .profile, put into .bashrc. The X startup problem would be solved BUT dnvm would only work when the user opens up a terminal. It would not be called as soon as the user logs in. Is that an issue? 
2. Make dnvm.sh work in Dash Shells (bye bye [[ ]] conditions and array looping )
3. Detect wether the /bin/sh is linked to bash or dash and behave accordingly

**Comment by glennc** [comment]
Ok, finally have a chance to come back to this. What I am thinking is that we should remove the following from dnvminstall.sh: https://github.com/aspnet/Home/blob/dev/dnvminstall.sh#L54-L55

Given that we don't really test dnvm on anything other than zsh and bash at the moment sourcing it in .profile seems dangerous. 

@anurse @BrennanConroy @lgtelles  Do you guys agree?

**Comment by BrennanConroy** [comment]
:+1:

**Comment by anurse** [comment]
I agree. The only thing to watch out for is that Mac OS X always starts a login shell when you open Terminal.app. We'll need to test for and handle that case.

**Comment by lgtelles** [comment]
Is it possible that $PROFILE returns the .profile? 
If so, we'd need to prevent that from reaching the lower part of the code, too

**Comment by lgtelles** [comment]
Well, should I then remove this part of the IF while it waits for the full dnvm.sh to be portable?

**Comment by lgtelles** [comment]
Removed the .profile references from the dnvminstall.sh 

Should work fine now

https://github.com/aspnet/Home/pull/771

**Comment by glennc** [comment]
@anurse @BrennanConroy What do you guys think, given that some folks are working on making dnvm.sh more widely usable do you think this is worthwhile? It seems like what what we should be doing, given the side effect of breaking dnvm and the fact that dnvm is upgraded straight from GitHub.

**Comment by lgtelles** [comment]
News? @glennc

**Comment by gilles-leblanc** [comment]
I am posting here since I don't know if I should raise another issue or it's part of this issue. 
Yesterday I installed dnvm on a fresh Linux Mint 17.3 install. dnvm worked fine. 

When I rebooted my machine, I now can't start an X session and the logs details indicate an error with the dnvm.sh file (don't have access to the message right now since I am dual booting). 

My default shell is zsh if that makes a difference. 

It looks likes this error over here : http://unix.stackexchange.com/questions/217487/session-dont-initializing

Is this part of this existing issue?

EDIT: I commented out the dnvm line in my .profile and this allowed me to log into X again. I'll try putting the line in my .zshrc file. On the Unix stackexchange post I linked it is mentionned this could be solved by using standard sh scripting rather than bash.

**Comment by lgtelles** [comment]
Yep. This is it.

Have you managed to login again? Need any help?

2016-02-14 12:58 GMT-02:00 Gilles Leblanc notifications@github.com:

**Comment by gilles-leblanc** [comment]
Yes I managed to log back in again. Thanks for asking and offering to help :+1: 
I commented out the line in my .profile file. I then went to add it to my .zshrc and found out it was already there. So the fix was pretty simple.

**Comment by habil66** [comment]
Have the same problem but since I'm a Linux noob I dont even know how to open the .profile file so I can comment it out.

Maybe for future reference the user can be asked to comment out the lines causing the error automatically?
