### ISSUE TITLE
Display a friendly message when dnvm list can find no runtimes

### ISSUE THREAD

**Issue by muratg** [aspnet/dnvm#380]
Currently it just returns. We should consider putting a message like `You don't have any runtimes installed. You can use dnvm install or dnvm upgrade commands` or something.

**Comment by MattGal** [comment]
+1.

**Comment by Eilon** [comment]
Grammar wise, here's one: `No runtimes are installed. Use the dnvm install or dnvm upgrade commands to install a runtime.`

**Comment by muratg** [comment]
Awesome, thanks Eilon!

**Comment by anurse** [comment]
We should use up-for-grabs more and dnvm is a great place for that ;)

**Comment by mholo65** [comment]
I could at least do the SH variant.. Just need to get aquainted with the tests setup.

**Comment by anurse** [comment]
Sure! We'd be happy to accept a partial fix for SH and PS1 separately :). The tests are pretty straight forward, if you need help, feel free to start the PR, mention me and we can discuss it.

**Comment by glennc** [comment]
This has already been done in powershell. But I think it is missing in bash.

**Comment by glennc** [comment]
Putting it in the backlog, but we will merge a PR for this when you send it through :).
