### ISSUE TITLE
VS build stuck after dnvm upgrade

### ISSUE THREAD

**Issue by ggondim** [aspnet/dnvm#381]
I had updated dnx to latest version (clt-beta6) in a solution that was targeting clr-beta5. After this the solution is stuck on build forever.

I have tried dnvm upgrade, also cleared all runtimes folder and reinstalled latest runtime, and last repaired Visual Studio.

**Comment by glennc** [comment]
Does it build from the command line? Need to determine if this is just inside VS or if it is more generally broken.

**Comment by glennc** [comment]
Closing. Feel free to reopen if you get a chance to give us more details.
