### ISSUE TITLE
dnvm upgrade. Determining latest version Error

### ISSUE THREAD

**Issue by franciscojsr** [aspnet/dnvm#382]
Hello,

I followed the instructions to install dnx on macosx and when I do :   dnvm upgrade 
or other comands available, it doesn't work. What ever I do, shows:

$  dnvm upgrade
Determining latest version
Error: Could not find latest version from feed https://www.nuget.org/api/v2

I followed others solutions that I read in others issues, i tried all, but doesn't work anything.

I tried doing with http feed  --> http://www.nuget.org/api/v2:
 dnvm upgrade DNX_FEED=http://www.nuget.org/api/v2

but shows other error after doing some things: 
HTTP Error  fetching dnx-mono.1.0.0-beta6 from http://www.nuget.org/api/v2

Why it this happen? It can be fixed?

**Comment by BrennanConroy** [comment]
What instructions did you follow? What version of dnvm do you have?

**Comment by franciscojsr** [comment]
I followed the Getting Started with ASP.NET 5 and DNX --> https://github.com/aspnet/home#os-x
The dnvm version is --> Version 1.0.0-beta7-10405

**Comment by BrennanConroy** [comment]
I can't repro this. Maybe nuget was having issues when you tried? Or you are using a different terminal than we usually use?

**Comment by franciscojsr** [comment]
Well, I tried several times since yesterday. I use the Terminal on mavericks.

**Comment by glennc** [comment]
@franciscojsr Is this still a problem or does it work now? I want to blame NuGet.org for having some sort of temporary outage. But if it is persistent on your machine then that is unlikely.

**Comment by franciscojsr** [comment]
Hi!  Yes, still it doesn't work. If it doesn't have solution i'll leave aspnet, dnvm, dnx, and VS Code.

**Comment by BrennanConroy** [comment]
Could you show the output for ```dnvm install 1.0.0-beta6 -OS osx -r mono```

**Comment by franciscojsr** [comment]
Shows the same errors! Here it's the output: 
Doing --> 
![captura de pantalla 2015-08-05 a la s 17 51 54](https://cloud.githubusercontent.com/assets/6168223/9090479/b9a7a88e-3b9a-11e5-9846-ab6c959b6116.png)

Shows --> 
![captura de pantalla 2015-08-05 a la s 17 51 29](https://cloud.githubusercontent.com/assets/6168223/9090496/c8139eaa-3b9a-11e5-8da4-697338f471a9.png)

And doing -->
![captura de pantalla 2015-08-05 a la s 17 55 34](https://cloud.githubusercontent.com/assets/6168223/9090587/63706c66-3b9b-11e5-8fd2-73f72073d4ed.png)

Shows --> 
![captura de pantalla 2015-08-05 a la s 17 56 20](https://cloud.githubusercontent.com/assets/6168223/9090592/6be44b74-3b9b-11e5-963b-d492f9f93939.png)

With http It's created in the runtimes folder a file ".nupkg" only.

**Comment by BrennanConroy** [comment]
Looks like you have some 'head' command other than what it expected. https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/head.1.html this is the 'head' command that is supposed to be used.

**Comment by franciscojsr** [comment]
I have this version:
![captura de pantalla 2015-08-05 a la s 18 25 36](https://cloud.githubusercontent.com/assets/6168223/9091286/a7602e6c-3b9f-11e5-8cc2-f7cb55274ab4.png)

**Comment by glennc** [comment]
What version of OS X is this?

**Comment by glennc** [comment]
Just realized you already told us it was mavericks. The issue here is that we are using head, with -n, and for some reason that doesn't work on your machine. Either because the mavericks version of head doesn't have that switch or because on your machine head is not the default one that comes with the OS but something else you've installed.

Do you know which? Does the head man page have -n on your machine?

**Comment by franciscojsr** [comment]
Yes, Mavericks.

man head prints :
![captura de pantalla 2015-08-12 a la s 20 10 52](https://cloud.githubusercontent.com/assets/6168223/9232488/4e4e1a3e-412e-11e5-8946-2d6b541bc662.png)

but head -h prints:
![captura de pantalla 2015-08-12 a la s 20 12 56](https://cloud.githubusercontent.com/assets/6168223/9232593/d3ef0630-412e-11e5-8fe9-b0e29fc5a015.png)

**Comment by franciscojsr** [comment]
I have install XAMPP. Can be the problem because that?

**Comment by dougbu** [comment]
Looks like your `PATH` and `MANPATH` environment variables are not aligned. Move the XAMPP location later in your path. That should fix it.

**Comment by franciscojsr** [comment]
Yes, thanks everyone! Finally. It's fixed. I already had XAMPP in my PATH from '.bash_profile', and that was the problem. I use Laravel with some apache configuration from XAMPP. I removed from my PATH, and 'head' it's the default. Thanks!
