### ISSUE TITLE
dnvm.sh:  syntax error near unnexpected token `<'

### ISSUE THREAD

**Issue by pranavkm** [aspnet/dnvm#386]
I'm receiving this error when executing dnvm.sh:

line 539: syntax error near unnexpected token `<'
line 539: `                                   read versionOrAlias downloadUrl < <(__dnvm_find_latest "$runtime" "$arch" "$os")'

This is being executed on an arm mx6 running Yocto. 
This had been executed successfully until late last week. (7/30/15).

Ported from https://github.com/aspnet/Home/issues/807

**Comment by mholo65** [comment]
Seem's like the shell you are running doesn't support [Process Substitution](http://tldp.org/LDP/abs/html/process-sub.html)

What shell are you using?

**Comment by cgershman** [comment]
That was the problem. I was using the basic shell that is built into Yocto. I switched to bash and that solved the problem.

**Comment by glennc** [comment]
Yeah, basic shells like Dash don't really work with the syntax we use in DNVM.sh. Not a great deal we can do about that I don't think. Bash and ZSH are the two that we test on.

**Comment by johnkors** [comment]
I get this error using zsh as well, though. 

```
This will install Mono, DNVM and DNX. Continue (y/n)? : y
*** Installing dev prereqs
*** MONO (runtime)
Warning: mono-4.2.0.179 already installed
*** DNVM (.NET version manager)
dnvm is already installed in /Users/johnkors/.dnx/dnvm, trying to update

=> Source string already in /Users/johnkors/.bash_profile
=> Source string already in /Users/johnkors/.zshrc
Type 'source /Users/johnkors/.dnx/dnvm/dnvm.sh' to start using dnvm
/Users/johnkors/.dnx/dnvm/dnvm.sh: line 539: syntax error near unexpected token `<'
/Users/johnkors/.dnx/dnvm/dnvm.sh: line 539: `                   read versionOrAlias downloadUrl < <(__dnvm_find_latest "$runtime" "$arch" "$os")'
*** SOURCERY
/Users/johnkors/.dnx/dnvm/dnvm.sh: line 539: syntax error near unexpected token `<'
/Users/johnkors/.dnx/dnvm/dnvm.sh: line 539: `                   read versionOrAlias downloadUrl < <(__dnvm_find_latest "$runtime" "$arch" "$os")'
```

I get this when running a simple shell script in zsh.

```
#!/bin/sh
read -p "This will install Mono, DNVM and DNX. Continue (y/n)? : " go
if [[ ! $go =~ ^[Yy]$ ]]
then
    echo "No install selected. Exiting.."
    exit 1
fi
echo "*** Installing dev prereqs"
echo "*** MONO (runtime)"
brew install mono
echo "*** DNVM (.NET version manager)"
curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh
echo "*** SOURCERY"
source ~/.dnx/dnvm/dnvm.sh
echo "DNX (NET Execution Environment)"
dnvm upgrade
```
