### ISSUE TITLE
dnvm list inconsistent between Win and *nix/OSX

### ISSUE THREAD

**Issue by mholo65** [aspnet/dnvm#390]
Column order is different when using -detailed flag.

dnvm.sh uses:
```
"Active" "Version" "Runtime" "Architecture" "OperatingSystem" "Alias" "Location"
```

and dnvm.ps1 uses;
```
"Active" "Version" "Runtime" "Arch" "OperatingSystem" "Location" "Alias"
```

As you can see from the above, Arch is used on *nix/OSX while Architecture is used on WIn

**Comment by BrennanConroy** [comment]
Thanks for catching that, I'll fix it shortly. If you find anymore inconsistencies please tell us.
