### ISSUE TITLE
make dnvm.sh portable

### ISSUE THREAD

**Issue by aggieben** [aspnet/dnvm#394]
While I get that by far, the most popular posix shell is bash, there are going to many a number of us out here in the interlands that don't use it for various reasons.  In my case specifically, the default shell in my docker containers is dash.

Unfortunately, `dnvm.sh` is not portable to other implementations of posix shell and requires bash-specific features.  It would be more desirable for this script to not take a dependency on bash.

**Comment by anurse** [comment]
We do support zsh as well and test it in both bash and zsh automatically, but dash has come up a few times now. The first step would be getting dash installed on our Linux build servers and running the tests there. Then we can fix the failing tests and run them on every build, ensuring we don't break dash compatibility.

Are you interested in giving some of this a shot? Obviously we need to take on the work of ensuring our build server has dash, but are you up for trying to remove the bash-isms from dnvm.sh?

/cc @BrennanConroy - AFAIK, it should be simple to install dash on our build server, as long as it's in APT.

**Comment by aggieben** [comment]
I'll see if I can make time for it this week.

**Comment by mholo65** [comment]
One possibility could also be to run tests in POSIX mode with bash (```--posix``` flag enabled). This should make ```dnvm.sh``` highly portable.

**Comment by glennc** [comment]
Linking to this: https://github.com/aspnet/dnvm/issues/376

**Comment by aggieben** [comment]
I've started to pick at this a bit.  I'll be pushing changes to [aggieben/dnvm (sh-portable)](https://github.com/aggieben/dnvm/tree/sh-portable).  There are a _lot_ of bashisms there that will need updating, no idea how many will be trivial vs how many won't.
