### ISSUE TITLE
dnu not executable by default

### ISSUE THREAD

**Issue by Daniel15** [aspnet/dnvm#397]
After running "dnvm upgrade -unstable", `dnu` is not executable:

```
danlo-mbp1:TagHelperSample.Web danlo$ dnu restore
-bash: /Users/danlo/.dnx/runtimes/dnx-mono.1.0.0-beta7-12364/bin/dnu: Permission denied
```

I needed to manually `chmod +x` to get it to work.

**Comment by davidfowl** [comment]
Update your dnvm

**Comment by BrennanConroy** [comment]
Closing since this has been fixed.

If you update your dnvm and still get bad dnu when upgrade/installing then reopen.
