### ISSUE TITLE
dnvm use default -r coreclr does not work

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnvm#405]
default is 1.0.0-beta8-15120 mono
use default -r coreclr should try to use 1.0.0-beta8-15120 coreclr but it just says adding the mono one to path

**Comment by glennc** [comment]
Isn't there a bug for this already? @DamianEdwards was complaining about it right?

**Comment by BrennanConroy** [comment]
He was complaining, but I don't think there was an issue for it.

**Comment by bricelam** [comment]
I'm seeing this on Windows too:

![image](https://cloud.githubusercontent.com/assets/1226749/9611520/f3dbccd8-5094-11e5-9f4f-1368441ca26a.png)

**Comment by bricelam** [comment]
It finally got annoying enough for me to take a stab at fixing it. :wink:
