### ISSUE TITLE
Set Environmental Path to override the KRE_NUGET_API_URL should trim the ""

### ISSUE THREAD

**Issue by JaneZhouQ** [aspnet/dnvm#41]
When I set the KRE_NUGET_API_URL to override the feed installation path to use the release feed rather than VNext feed,  I have use the environment set command to set it to "https://www.myget.org/F/aspnetvnext/api/v2".  However, it takes in the ""  literally into the environment variable.  The Subsequent command to run KVM install actually failed the command complaining the following unclear error message.

Downloading KRE-svr50-x86.KRE-svr50-x86.1.0.0-alpha2-10030 from "https://www.myg
et.org/F/aspnetrelease/api/v2"
Exception calling "DownloadFile" with "2" argument(s): "Illegal characters in path."

**Comment by muratg** [comment]
DNVM should now have the correct behavior.
