### ISSUE TITLE
Creation of DEB, RPM, and PKGNG files for UNIX/Linux systems

### ISSUE THREAD

**Issue by wholroyd** [aspnet/dnvm#417]
This was originally asked for over in https://github.com/aspnet/Home/issues/437 back in April and just realized there is a dedicated repo for DNVM now.

The challenge of making these packages is that DNVM expects to be installed on a per-user basis today which all UNIX/Linux package managers don't support without hackery in the package. I think it should be considered that DNVM install runtimes at a system level and then a choice of active/default/{alias} be configured on a per-user basis, for moth Windows and UNIX/Linux alike.

I started working on this already and came up with a Docker image that builds the .rpm and .deb packages using the current version of the DNVM script as of this posting, and manages the runtimes and active/default/{alias} at system level.

https://github.com/wholroyd/dnvm

Both packages install DNVM at a system level into `/usr/local/bin/dnx/` and it creates a shell script into `/etc/profiles.d/` that sets up $PATH to know where DNVM is located (look at the `dnx.sh` file in the repo).

Contents of the RPM...

```
[root@22911933e21f data]# rpm -qp dnvm-1.0.0_beta8_15502-1.x86_64.rpm -l
/etc/profile.d/dnx.sh
/usr/local/bin/dnx/dnvm/dnvm.sh
/usr/local/bin/dnx/runtimes
```

I'm using [FPM](https://github.com/jordansissel/fpm) to do the magic which already supports RPM, DEB, PKG (Solaris), and OSXPKG (Mac OS X). The PKGNG format for FreeBSD will be supported in the future. The OSXPKG format requires a Mac however - a typical Apple development restriction.

**Comment by wholroyd** [comment]
The paths were changed from `/usr/local/bin` to `/usr/bin/`

**Comment by pruiz** [comment]
Hi,

I would use '/usr/lib/dnx/*' as base directory for dnx files & runtimes, as this alings a bit better with LFHS (IMHO).
