### ISSUE TITLE
dnvm alias -d (not working in Linux) also missing help

### ISSUE THREAD

**Issue by npateman** [aspnet/dnvm#418]
Hi there,

The following command

dnvm alias -d default

works in Windows, with the following output

Removing alias default

In Linux, the very same command gives the default framework an alias of 'd'.

Also the command dnvm alias help doesn't produce any help, instead it says

"There is no alias called 'help'"

**Comment by mholo65** [comment]
Up for grabs?

**Comment by muratg** [comment]
@dougbu Are you able take this one as well?

**Comment by dougbu** [comment]
:ok:

**Comment by mholo65** [comment]
@dougbu I have a PR waiting for you here #452

**Comment by dougbu** [comment]
16530be

**Comment by dougbu** [comment]
Will include in an RC1 announcement when we wrap #455.
