### ISSUE TITLE
regression: dnvm trying to write to /usr/local/lib/dnx/runtimes

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnvm#421]
I have my dnvm installed in my user profile. If I do ```dnvm update-self``` it will try to download the script to the global install directory ```/usr/local/lib/dnx/runtimes``` which does not exist since my dnx is installed in ```$HOME/.dnx```. Shouldn't teh user profile install folder be given priority if it exists and the global install location doesn't?

**Comment by borgdylan** [comment]
I never set the variable in the first place.

**Comment by muratg** [comment]
@BrennanConroy I repro'd this on my Mac, had beta5 dnvm.

**Comment by borgdylan** [comment]
I had quite a recent one. The issue persists with the latest dnvm as well.

**Comment by BrennanConroy** [comment]
I tried with beta8-15502 and it successfully updates to beta8-15508, there is a error message at the end which we should fix but it does update.

**Comment by BrennanConroy** [comment]
Why did you close this?

**Comment by borgdylan** [comment]
Because you said that there was no bug, just a spurious error message. In fact the update process worked as you said.
