### ISSUE TITLE
`dnvm run ...` and `dnvm exec` do not set exit code correctly

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnvm#428]
`dnvm run` and `dnvm exec` do not pass a non-`0` exit code from `dnx` back to the shell. (Side note: This and the `_k-test.shade` / `_k.shade` approach means DNX Core tests on Windows can fail without ending the build.)

Repro steps
1. create a simple Console application that always fails
2. `dnu restore`
3. `dnx run`
4. echo %ErrorLevel%`
  - observe expected `1`
5. `dnvm run default run` or `dnvm exec default dnx run`
6. `echo %ErrorLevel%`
  - observe *unexpected* `0`

Example program
``` c#
namespace ExitCode
{
    public class Program
    {
        public int Main(string[] args)
        {
            return 1;
        }
    }
}
```

**Comment by muratg** [comment]
@dougbu Is this a regression?

**Comment by dougbu** [comment]
I don't think this ever worked correctly. Not sure why we changed KoreBuild as if it did. @BrennanConroy ??

**Comment by BrennanConroy** [comment]
4f0b0994091d934de8ea316d31c4a51a56c1932c
