### ISSUE TITLE
On Ubuntu 14.04 LTS, dnvm help | less is unreadable, while dnvm help | more looks fine

### ISSUE THREAD

**Issue by VanKichline** [aspnet/dnvm#429]
The output of `dnvm help` is too long to read in a small terminal window, so it's natural to try `dnvm help | less` on Ubuntu.  I have never run into an issue with this before, but do with dnvm.  
Note that `dnvm help | more` is fine. This might be considered a `less` bug, but it's certainly uncommon.  Could it be avoided?

dnvm help | more:
![more](https://cloud.githubusercontent.com/assets/14066157/9754478/84724ac6-567e-11e5-9e62-894e95a7faf8.png)

dnvm help | less:
![less](https://cloud.githubusercontent.com/assets/14066157/9754494/9595ca1c-567e-11e5-8c71-6c13a22b005c.png)

**Comment by dougbu** [comment]
@VanKichline `less --raw-control-chars` should work in your situation. Not sure why `more` does this automatically.

**Comment by muratg** [comment]
On a Mac, both `more` and `less` display the control chars (and make the output less readable).  Passing `--raw-control-chars` solves the readability. 

Not much we can do on DNVM though, except not using the control chars at all and go monochrome. 

Closing this one.

**Comment by VanKichline** [comment]
Do you have to use control characters?  I don't have to include  --raw-control-chars for any other tool I use, and frankly would have to look it up to use it again.  
I think you added the colors to add value.  On Linux and Mac, it's having exactly the opposite effect.  If you did a survey of satisfaction with this decision on non-Windows clients, I bet you'd find that the colors aren't an asset.

**Comment by muratg** [comment]
`dnu restore` for example has the same problem.  We do not have customer surveys, but my personal experience is that colors do help readability. Especially when the output is very long (like in `dnu restore`'s case) you would want something that would help discern signals when you're quickly scanning the wall of text. (Do you turn off colors in Visual Studio while writing code? :trollface:)

BTW, `--raw-control-chars` has a shortcut: `-r`.  If you want to have `less` always have this on, you can put the following in your `.bashrc` or profile:

`export LESS="-r"` and the issue will be gone for `less`
`export MORE="-r"` and the issue will be gone for `more`

Additionally we're experimenting with some fundamental changes to `dnvm` itself, if we go that route, there's a plan to make the output of our tools (`dnvm`, `dnu`, `dnx`) consistent.  I'll make sure to bring this discussion there as well.  cc: @DamianEdwards @glennc
