### ISSUE TITLE
Allow to choose the version on the dnvm when updating

### ISSUE THREAD

**Issue by roysanchez** [aspnet/dnvm#430]
Currently can't choose the version of the dnvm to update.

Was trying to install beta7 but got beta8 as it's the latest.

**Comment by muratg** [comment]
Just curious, any reason you were trying to install beta7 specifically?

**Comment by roysanchez** [comment]
just curiosity, wanted to see the changes from beta7 to beta8

**Comment by muratg** [comment]
@roysanchez Thanks. I agree, this would be a nice feature. We're planning to have different ways of acquiring DNVM which would enable this too.

In the meantime, you can download the specific version from the repo directly if you'd like.

**Comment by muratg** [comment]
Putting this into the backlog for now.  There are workarounds, and we'll revisit if we have time before RTM.
