### ISSUE TITLE
DNU build give a error about missing namespace but VS2015RC has no problem compiling the source

### ISSUE THREAD

**Issue by Anderman** [aspnet/dnvm#432]
DNU build give this error:
`C:\git\DBC\src\DBC\Controllers\UserController.cs(77,24): DNX,Version=v4.5.1 error CS0118: 'DataTables' is a namespace but is used like a type`

for this line
```
            return new DataTables().GetJSonResult(
                z
                , dTRequest);
```
This can be fixed with adding a namespace
```
            return new Mvc.JQuery.Datatables.DataTables().GetJSonResult(
                z
                , dTRequest);

```
dnvm used
`.NET Version Manager v1.0.0-beta7-10400`

dnu build
`Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532`

**Comment by davidfowl** [comment]
Can you open this bug on aspnet/dnx. Also can you provide step by step instructions on how to reproduce this error?
