### ISSUE TITLE
dnvm help command is different with others

### ISSUE THREAD

**Issue by doggy8088** [aspnet/dnvm#437]
In `dnvm`, to query a help docs about a command, you have type `dnvm help <commandname>`.   But in `dnu` and `dnx`, their help docs is add a `--help` switch.  Are you going to have consistent command usage style in the future?

**Comment by muratg** [comment]
Yes, we're considering unifying the experience. Putting this in 1.0.0 backlog so that we can revisit before RTM.

**Comment by doggy8088** [comment]
Thanks!
