### ISSUE TITLE
Detect distro in order to install correct distro-specific package

### ISSUE THREAD

**Issue by anurse** [aspnet/dnvm#443]
Right now, on Linux we just assume the default os value should be `linux`. As per aspnet/dnx#2730 though, this will not work in the future. We should use the `/etc/lsb-release` file to detect which of our supported distros we are on and use that as the default

/cc @BrennanConroy @muratg @moozzyk @davidfowl

**Comment by MarcusLlewellyn** [comment]
It may be worth noting that Debian relies on the lsb_release command. There is no /etc/lsb-release file.
