### ISSUE TITLE
Package generated by 'dnu pack' fails to upload on NuGet.org

### ISSUE THREAD

**Issue by acastaner** [aspnet/dnvm#447]
I'm trying to publish a package of [this repo](https://github.com/ribandelle/MusicBrainz.DNX) on Nuget.org. For this I'm using the `dnx pack` command, which runs successfully:
```
MusicBrainz.DNX -> C:\Users\acastaner\Documents\GitHub\Ribandelle\MusicBrainz\MusicBrainz.DNX\bin\Debug\MusicBrainz.DNX.1.0.0.nupkg
MusicBrainz.DNX -> C:\Users\acastaner\Documents\GitHub\Ribandelle\MusicBrainz\MusicBrainz.DNX\bin\Debug\MusicBrainz.DNX.1.0.0.symbols.nupkg

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.8653998
Total build time elapsed: 00:00:00.8740383
Total projects built: 1
```
However when I try to upload the generated file (`MusicBrainz.DNX.1.0.0.nupkg`) I'm getting an error:

```Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest.```

Are there any extra steps required? The `dnu pack -h` command doesn't provide any I can see, like the `nuget pack <project file>`. I'm using DNVM 1.0.0-beta8-15516 on a beta7 project.

**Comment by BrennanConroy** [comment]
Could you file this in the dnx repo and give the dnx version

**Comment by acastaner** [comment]
Deleting the whole .dnx directory and reinstalling fixed my issue, I must have had an old version that stuck around for some reason.
