### ISSUE TITLE
Alias -r is case sensitive

### ISSUE THREAD

**Issue by glennc** [aspnet/dnvm#449]
`dnvm alias default -r CoreCLR` will create an alias but then not work correctly due to the case.

It should either fail and tell me that the casing is wrong or actually work. Ideally it would work, perhaps lowering all the runtime names since they are all lower case in the file names.

**Comment by mholo65** [comment]
Up for grabs? I could have a look at it.

**Comment by muratg** [comment]
@mholo65 Sure, thanks!

**Comment by mholo65** [comment]
@glennc Isn't version missing from your description? I.e. shouldn't the command be e.g. ```dnvm alias default 1.0.0-beta7 -r CoreCLR```

**Comment by mholo65** [comment]
How about other commands? E.g. ```dnvm install latest -r CoreCLR``' will also fail?

**Comment by glennc** [comment]
`dnvm install default -r coreclr` will take the version and other information from the default alias.

This is a useful feature that often gets overlooked :).

Yes, seems likely it is a problem everywhere and should be fixed everywhere.

**Comment by muratg** [comment]
:+1:  It would be great if we could be 100% consistent with this
