### ISSUE TITLE
[Discussion] Changes to `dnvm` parameters

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnvm#456]
- The `-alias` parameter to `dnvm install` must now be spelled out completely. (This supports the `-arch` consistency mentioned below.)
- [Linux] `dnvm unalias` is deprecated. Please use `dnvm alias -d` instead. (These subcommands now match Windows.)
- `-a` is the short form in all subcommands for `-arch`.
  - [Windows] The longest `-architecture` form of this parameter remains available.
- [Windows] `-g` (for `-global`), `-p` (for `-persistent`) and `-u` (for `-unstable`) short forms are now supported in all subcommands which include those parameters. (This matches the short forms allowed on Linux.)

**Comment by dougbu** [comment]
This issue is intended for discussion of aspnet/Announcements#76.

**Comment by dougbu** [comment]
See also
- #418, issue about `dnvm alias -d` not working on Linux
- #452, PR fixing #418
- #419, PR making short forms consistent in `dnvm.sh`
- #455, PR extending #419 to include consistency in `dnvm.ps1`

Note #419 and #455 have no specific issue. However subcommand inconsistencies have been noted in a number of issues in this repo.

**Comment by rossipedia** [comment]
> [Windows] The longest `-archicture` form of this parameter remains available.

Is that a typo? Or is the parameter actually misspelled in the source code?

**Comment by dougbu** [comment]
Typo that I'll fix. Much appreciated.
