### ISSUE TITLE
dnvm upgrade -f does not force upgrade on linux

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/dnvm#459]
From the description from of the `-force` option for dnvm upgrade, it seems like the the behaviour should be to delete the runtime if it exists already and do a fresh install. Currently, the behaviour is that if the runtime is already up to date, just update the default alias. Either the description or the behaviour should be updated.

As tested on linux:
![image](https://cloud.githubusercontent.com/assets/2030323/10230055/136549f0-6830-11e5-9d3f-717429c5fd9a.png)

Note that the first upgrade -f was called when no runtimes were installed so deleting the directory also seems unnecessary.

**Comment by shirhatti** [comment]
Could not repro this on Windows
