### ISSUE TITLE
Command name collision with "kvm" command from Linux Kernel-based Virtual Machine

### ISSUE THREAD

**Issue by directhex** [aspnet/dnvm#46]
The command "kvm" has been in use since 2007 as a platform for running virtual machines on Linux with hardware acceleration.

The PATH environment on Linux is a flat namespace, so it is not possible to offer two different applications with the same command name.

It will be awkward to offer ASP.NET KVM as a standard feature in Linux package managers, without renaming the command to something else like "aspkvm", which will be tedious and painful as far as documentation goes for all concerned.

The relative sizes of the communities have no bearing - for example, the Node.js maintainers in Debian Linux were forced to rename the "node" command in Debian-only, to avoid collision with a ham radio app from the 1990s which was already using "node".

It's still very early days for ASP.NET KVM - please consider renaming the command globally, rather than requiring the command to be slightly different in a few places for a few users.

**Comment by Praburaj** [comment]
There is a bigger discussion happening on naming here https://github.com/aspnet/Home/issues/261

**Comment by muratg** [comment]
Renamed to dnvm.
