### ISSUE TITLE
Dnvm doesn't work inside Package Console Manager

### ISSUE THREAD

**Issue by mortezadalil** [aspnet/dnvm#475]
VS2015
Windows8.1

![2015-10-10_194642](https://cloud.githubusercontent.com/assets/15077932/10418155/1d06ee40-7060-11e5-9234-5d42826681a4.jpg)
![2015-10-10_194442](https://cloud.githubusercontent.com/assets/15077932/10418156/1e3ee2ae-7060-11e5-996f-7a24f3b80d42.jpg)

**Comment by alzdrak** [comment]
As stated in: https://stackoverflow.com/questions/33056133/dnvm-command-inside-package-console-manager-doesnt-show-anything

Commands are running, however its not returning any ouput.

**Comment by Domysee** [comment]
I have a similar issue. However, in my case dnvm list worked, until I executed dnvm update-self. After that the list command didnt output anything anymore.

**Comment by Huck** [comment]
same here. windows 7 and VS.NET 2015.

running dnvm commands in package manager console does not display anything but commands run fine.

**Comment by Ruberoid** [comment]
Same issue. Output on any command applied to vs2015sp1 Windows 7 x64 package manager console to DNVM command is empty
