### ISSUE TITLE
Trouble switching runtime with alias

### ISSUE THREAD

**Issue by TJSoftware** [aspnet/dnvm#483]
You can see in the attached screenshot that I first created an alias.  I then listed to see where Active was.  I attempted to use the command `dnvm use <alias>` to switch the active runtime.  I ran dnvm list and the active had not been changed.  To verify that I could change the active I used the full runtime version, runtime, and architecture.  I ran another list after that to confirm and the active runtime was updated.

![aliasissuecleaned](https://cloud.githubusercontent.com/assets/4823412/10832867/94c35940-7e53-11e5-823e-a98ddba0b73c.PNG)

**Comment by BrennanConroy** [comment]
What version of dnvm

**Comment by TJSoftware** [comment]
.NET Version Manager v1.0.0-beta5-10384

**Comment by BrennanConroy** [comment]
That is a very old version, this bug has already been fixed

**Comment by TJSoftware** [comment]
Ahh, thanks for letting me know.  I will upgrade, I must have got confused on what VM I was on.

**Comment by TJSoftware** [comment]
I ran a `dnvm upgrade` but the version was the same.  I also tried `dnvm upgrade -u`.  Is this the incorrect command to upgrade the dnvm?

**Comment by BrennanConroy** [comment]
dnvm update-self

**Comment by TJSoftware** [comment]
Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
dnvm-update-self : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1:1453 char:13
+             & "dnvm-$cmd" @cmdargs
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [dnvm-update-self], MethodInvocationException
    + FullyQualifiedErrorId : WebException,dnvm-update-self

**Comment by BrennanConroy** [comment]
You probably have one of the bad versions where update-self was broken, you'll have to manually update it from the Home repo

**Comment by TJSoftware** [comment]
Ok, thanks for the fast responses.  I will get the latest.

**Comment by TJSoftware** [comment]
P.S. When in doubt turn it off and on.  I closed the command prompt and reopened.  At that point the `dnvm update-self` worked.  My current version is .NET Version Manager v1.0.0-rc1-15535.

**Comment by TJSoftware** [comment]
I was also able to confirm that this is fixed in the latest version.

**Comment by cda-1** [comment]
For any googlers, try in an admin command prompt. That fixed the issue for me.

**Comment by TJSoftware** [comment]
@cda-1 I also found that while on beta5 you need to upgrade to beta8 before this works.  Here is a link to upgrade to beta8. https://www.microsoft.com/en-us/download/confirmation.aspx?id=49442
