### ISSUE TITLE
Show error message when no global.json or project.json could be found

### ISSUE THREAD

**Issue by cH40z-Lord** [aspnet/dnvm#486]
When accidentally executing `dnu` restore in a classic .NET project which still uses `packages.config` no error message or hint is printed by `dnu` when trying to restore packages as you can see below.

![dnu restore](http://i.imgur.com/fumzvOr.png)

IMO, to enhance the entire user experience, at least an error including a hint should be printed.

**Comment by BrennanConroy** [comment]
Log on dnx repo
