### ISSUE TITLE
DNVM use

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/dnvm#489]
perhaps I miss something . expected behaviour is * at line coreclr

c:\users\xxx\documents\visual studio 2015\Projects\ConsoleApp1test\src\ConsoleApp1test>dnvm use -p hannes
Adding C:\Users\xxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin to process PATH
Adding C:\Users\xxx\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin to user PATH

c:\users\xxx\documents\visual studio 2015\Projects\ConsoleApp1test\src\ConsoleApp1test>dnvm list

Active Version         Runtime Architecture Location                   Alias
------ -------         ------- ------------ --------                   -----
       1.0.0-beta5     clr     x64          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta5     clr     x86          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta5     coreclr x64          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta5     coreclr x86          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta8     clr     x64          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta8     clr     x86          C:\Users\xxx\.dnx\runtimes default  *
       1.0.0-beta8     coreclr x64          C:\Users\xxx\.dnx\runtimes
       1.0.0-beta8     coreclr x86          C:\Users\xxx\.dnx\runtimes hannes
       1.0.0-rc1-15838 coreclr x86          C:\Users\xxx\.dnx\runtimes peter

Moved the * to end of line, cause of markdown formatting

**Comment by BrennanConroy** [comment]
Version of dnvm?

**Comment by hannespreishuber** [comment]
.NET Version Manager v1.0.0-beta5-10384

**Comment by hannespreishuber** [comment]
OK did the upgrade with upgrade and upgade-self  now it works
