### ISSUE TITLE
DNVM Setup fails to set process path

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/dnvm#490]
Currently reproed on Win 10, will try on Win 7

**Comment by bricelam** [comment]
Were you using PowerShell or Command Prompt?

**Comment by BrennanConroy** [comment]
CMD

**Comment by j0nnyhughes** [comment]
Is this because https://github.com/aspnet/Home/blob/dev/dnvm.cmd calls the actual install with "Powershell -Command{...}" creating a new process and therefore setting the path there instead of the main process being used by the user or build server for example?

**Comment by bricelam** [comment]
@jonnyh89 That was my theory too, but it looks like there is code to copy the values to a batch file and invoke that after PowerShell has exited.
