### ISSUE TITLE
After setting up kvm, kvm list returns empty when no KRE's are installed

### ISSUE THREAD

**Issue by balachir** [aspnet/dnvm#50]
1. Clean Windows machine
2. Install kvm using powershell script from github.com/aspnet/Home
3. Open a new command prompt and do 'kvm list'

ACTUAL
kvm list returns empty when no KRE's are installed. Should it give some message instead? I had one user ask me why nothing is listed.

![image](https://cloud.githubusercontent.com/assets/8246794/4001173/34228a68-2961-11e4-8bb2-a4adadcf9f4e.png)

**Comment by davidfowl** [comment]
@glennc Didn't you work on this in a branch?

**Comment by glennc** [comment]
This is fixed in newer versions of DNVM.
