### ISSUE TITLE
Provide feed management for kvm

### ISSUE THREAD

**Issue by suhasj** [aspnet/dnvm#71]
As discussed in the meeting, providing two additional formulae for feed management in kvm

- kvm source

- kvm source &lt;new source&gt;

**Comment by anurse** [comment]
Reviving this now. My thought is something similar to "channels" in Chrome. The commands would be very similar to the management of "remotes" in Git

```
> kvm channel
* dev      https://myget.org/F/aspnetdev
  release  https://myget.org/F/aspnetrelease
> kvm channel use release
> kvm channel
  dev      https://myget.org/F/aspnetdev
* release  https://myget.org/F/aspnetrelease
> kvm channel use \\myshare\kres
... "uses" an anonymous channel defined by URL alone
> kvm channel
  dev      https://myget.org/F/aspnetdev
  release  https://myget.org/F/aspnetrelease
*          \\myshare\kres
> kvm install latest
... installs latest from active channel/feed ...
> kvm channel add mykres https://mycorp.com/mykres
> kvm channel
  dev      https://myget.org/F/aspnetdev
  release  https://myget.org/F/aspnetrelease
*          \\myshare\kres
  mykres   https://mycorp.com/mykres
> kvm channel rm dev
... remove a channel ...
> kvm channel add release ...
... adding a channel that already exists would replace the channel
```

KVM would include the "dev" and "release" channels pointing at the various official myget feeds. The channel list would be persisted in simple text files in `~/.kre/channels`, much like aliases. The active channel should probably be persisted in a per-shell environment variable (`KVM_CHANNEL` or something). That means it would also be possible to have machine and user level defaults by simply resetting those variables at those contexts.

An extra feature we could consider is allowing `kvm install` to accept a channel name or URL to use, ignoring the active channel. I'm less sure of the usefulness of this.

```
> kvm install dev:latest
... regardless of active channel, installs latest from dev channel ...
> kvm install dev:1.0.0-beta2
... etc ...
```

Thoughts? /cc @glennc @davidfowl @lodejard @Praburaj @suhasj

**Comment by Praburaj** [comment]
+1 on this. Same as my original proposal https://github.com/aspnet/kvm/issues/52.

**Comment by glennc** [comment]
I think channels is the better approach, ideally with the extra feature at the end. The issue with the simpler approach we started with is that for the people that need this it isn't any easier than a second kvm file in the path.  And the people that don't need this feature never see it anyway so it being slightly more complicated isn't that big an issue.

**Comment by anurse** [comment]
We ended up with `-u` to switch to the unstable feed for now.
