### ISSUE TITLE
kvm confuses about KRE bin path after KRE got installed in ProgramFiles KRE location

### ISSUE THREAD

**Issue by Xiaohongt** [aspnet/dnvm#85]
Once run kvm with -g parameter to install KRE in ProgramFiles KRE location, after that, when run kvm without -g to install kvm, it still adds ProgramFiles KRE bin path to process/user path.

Repro steps:
1). D:\>kvm install latest -amd64 -g
Determining latest version
Downloading KRE-CLR-amd64.1.0.0-beta2-10614 from https://www.myget.org/F/aspnetvnext/api/v2
Unpacking to D:\Program Files\KRE\packages\temp
Installing to D:\Program Files\KRE\packages\KRE-CLR-amd64.1.0.0-beta2-10614
Adding D:\Program Files\KRE\packages\KRE-CLR-amd64.1.0.0-beta2-10614\bin to process PATH

2). D:\>kvm install latest -amd64
Determining latest version
Downloading KRE-CLR-amd64.1.0.0-beta2-10614 from https://www.myget.org/F/aspnetvnext/api/v2
Unpacking to D:\Users\xiaota\.kre\packages\temp
Installing to D:\Users\xiaota\.kre\packages\KRE-CLR-amd64.1.0.0-beta2-10614
Adding D:\Program Files\KRE\packages\KRE-CLR-amd64.1.0.0-beta2-10614\bin to process PATH

or 2). D:\>kvm upgrade -amd64
Determining latest version
Downloading KRE-CLR-amd64.1.0.0-beta2-10614 from https://www.myget.org/F/aspnetvnext/api/v2
Unpacking to D:\Users\xiaota\.kre\packages\temp
Installing to D:\Users\xiaota\.kre\packages\KRE-CLR-amd64.1.0.0-beta2-10614
Adding D:\Program Files\KRE\packages\KRE-CLR-amd64.1.0.0-beta2-10614\bin to process PATH
Adding D:\Program Files\KRE\packages\KRE-CLR-amd64.1.0.0-beta2-10614\bin to user PATH
Updating alias 'default' to 'KRE-CLR-amd64.1.0.0-beta2-10614'

Expected result:
In both repro step#2 without -g, kvm should add userprofile KRE bin path to process/user path.

Actual result:
In both repro step#2, kvm still add ProgramFiles KRE bin path to process/user path.

**Comment by muratg** [comment]
Should be fixed by now. Beta 6 sign-off activities should be covering this scenario.
