### ISSUE TITLE
kvm should use - for short options and -- for full named options

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnvm#89]
Just like `kpm`, `kvm` should use `--` for full named options.

Today:
`-g | -global`

Proposed:
`-g | --global`

**Comment by Praburaj** [comment]
@rlbisbe - typo has been fixed now. https://github.com/aspnet/kvm/commit/5ed15ec21e67bb23bd5ca771f2dc9de1be10681b. 

@victorhurdugaci if both `-` and `--` are valid ones do you think this item can be closed?

**Comment by muratg** [comment]
Closing since - and -- are valid
